### ISSUE TITLE
Fiche "Comment utiliser cette documentation" (dont doremifasolData)

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#107]
In GitLab by @oliviermeslin on Dec 4, 2020, 13:45

J'ouvre cette _issue_ car il me semble important que la documentation comprenne une fiche introductive sur "Comment utiliser cette documentation". Cette fiche aborderait notamment les points suivants:

- expliquer la structure de la doc;
- tous les exemples sont reproductibles;
- les jeux d'exemples viennent de insee.fr via `doremifasolData`;
- les fiches ne sont pas exhaustives, et il y a des références à la fin de chaque fiche;
- la doc est collaborative, tout le monde peut contribuer.

Je vois deux questions pas claires:

- Je ne sais pas s'il faut détailler le _package_ `doremifasolData` et son utilisation dans cette fiche introductive, ou faire une minifiche spécifique au début de la partie "Fiches Thématiques".
- Je ne sais pas s'il faut parler du _package_ `doremifasol` ou pas. On pourrait en faire une fiche séparée, à la condition qu'insee.fr devienne accessible depuis AUSv3. @pierre-lamarche : une opinion?

Je propose d'affecter @py_b sur cette _issue_ (sur la partie `doremifasolData` dans un premier temps).

**Comment by linogaliana** [comment]
In GitLab by @py_b on Dec 7, 2020, 09:25

> `doremifasolData` [...] dans cette fiche introductive, ou faire une minifiche spécifique au début de la partie "Fiches Thématiques"

Je pense qu'il n'y a pas assez à dire pour une fiche dédiée. Un petit paragraphe serait largement suffisant ? Pour plus d'explications, on renvoie vers la doc du package.

> Je ne sais pas s'il faut parler du *package* `doremifasol` ou pas.

Si oui, dans une fiche mentionnant les packages _Insee_ faits par des agents de l'Insee (doremifasol, [insee](https://inseefr.github.io/R-Insee-Data/), [COGugaison](https://antuki.github.io/COGugaison/), [apinsee](https://inseefrlab.github.io/apinsee/)...) ?

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Dec 7, 2020, 17:17

> Je pense qu'il n'y a pas assez à dire pour une fiche dédiée. Un petit paragraphe serait largement suffisant ? Pour plus d'explications, on renvoie vers la doc du package.

Tu as raison @py_b, on ne va pas faire une fiche entière sur `doremifasolData`, mais simplement un paragraphe sur le _package_. En revanche, on peut expliquer la structure de la documentation, le fait que chaque fiche commence par des recommandations, que la plupart des exemples reposent sur des données Insee, que tous les exemples sont reproductibles grâce à `doremifasolData`... Et on peut donner la liste des tables disponibles dans le _package_. Qu'en penses-tu? Tu te sens de rédiger un premier jet?

> Si oui, dans une fiche mentionnant les packages *Insee* faits par des agents de l'Insee (doremifasol, [insee](https://inseefr.github.io/R-Insee-Data/), [COGugaison](https://antuki.github.io/COGugaison/), [apinsee](https://inseefrlab.github.io/apinsee/)...) ?

Alors ce point est plus compliqué. Je pense pas qu'`utilitR` soit le bon endroit pour lister les _packages_ développés à l'Insee. En revanche, il me semblait qu'on pouvait faire une fiche sur "Utiliser `doremifasol` pour accéder à des données sur Insee.fr", car c'est bien une tâche standard réalisable avec `R`. A rediscuter!

**Comment by linogaliana** [comment]
In GitLab by @py_b on Dec 7, 2020, 23:55

mentioned in merge request !77

**Comment by oliviermeslin** [comment]
La fiche est terminée et déployée, je ferme.
