### ISSUE TITLE
Espaces et ponctuation

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#108]
In GitLab by @py_b on Dec 8, 2020, 09:09

Note pour plus tard :

En français, les signes de ponctuation "**?**", "**:**" et "**;**" sont précédés d'un espace, contrairement à la norme anglo-saxonne (pas d'espace). 

Il y aura de (nombreuses) petites finitions à faire dans ce sens.

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Dec 8, 2020, 09:35

Tu as raison, mais je pense qu'il ne faut pas modifier le code source des fiches. Je pense qu'il faut plutôt utiliser des options lors de la compilation (comme en LaTeX, où pour le coup c'est simple et efficace). Qu'en pensent @linogaliana et @RLesur ?

**Comment by oliviermeslin** [comment]
Réglé.
