### ISSUE TITLE
[Contributing] Comment créditer les contributeurs ?

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#16]
In GitLab by @linogaliana on Mar 17, 2020, 16:41

Dans le fichier `Description`, on peut ajouter le nom des contributeurs. Je lance ce *thread* pour réfléchir à la manière dont cela peut être fait pour que cela soit visible dans le `bookdown`

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Mar 17, 2020, 16:45

changed title from **Comment créditer les contributeurs ?** to **{+[Contributing] +}Comment créditer les contributeurs ?**

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Mar 17, 2020, 17:00

Bonne question. Je vois deux possibilités:

* On pourrait lister les contributeurs dans le champ `author` du fichier `index.Rmd` du `bookdown`? C'est expliqué [ici](https://bookdown.org/yihui/rmarkdown-cookbook/multiple-authors.html).
* On peut aussi vouloir que l'auteur général du `bookdown` soit l'Insee. En ce cas, on pourrait ajouter la liste des contributeurs dans `01_Intro/01_Intro.Rmd` sous la forme d'une phrase du genre: Les personnes suivantes ont participé à la rédaction de cette documentation: etc.

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Mar 17, 2020, 17:17

perso, je préfère être crédité en bitcoins.
ok, ok, je sors ...

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Mar 17, 2020, 17:23

Pour la peine je t'assigne une relecture.

**Comment by oliviermeslin** [comment]
J'ai proposé quelque chose dans 236e8491d. C'est très discret, on peut éventuellement faire un truc plus clinquant. @RLesur, @linogaliana : un avis?

**Comment by linogaliana** [comment]
On peut reprendre la section que tu as fait et la mettre en forme de manière à la détacher un peu mieux de l'introduction. 

Par exemple, on pourrait faire quelque chose d'un peu plus clinquant, sur le modèle de la documentation collaborative du SNDS (j'aime bien les *box* qu'ils proposent pour créditer les auteurs, par exemple [dans cette fiche](https://gitlab.com/healthdatahub/documentation-snds/-/blob/master/fiches/cartographie_pathologies.md)). Avec une icone du type de [celle-là](https://fontawesome.com/icons/feather-alt?style=solid)

**Comment by RLesur** [comment]
Effectivement, mettre les contributeurs dans un cadre, c'est une bonne idée.

**Comment by linogaliana** [comment]
Je ferme l'*issue* puisqu'il y a maintenant un cadre listant les contributeurs
