### ISSUE TITLE
[CI] Rendu du pdf

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#17]
In GitLab by @linogaliana on Mar 17, 2020, 16:47

Le *template* par défaut `LateX` doit être modifié pour limiter les problèmes de mise en page, entre autres :

* colonnes de tableaux
* morceaux de code qui dépassent de la fiche

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Mar 18, 2020, 13:10

@oliviermeslin pour pouvoir utiliser les box en `latex` il faut:

1. définir dans `preambule.tex` les box `recommandations` etc.
2. modifier les chunks de la manière suivante:

```markdown
::: {.recommandation data-latex=""}
**Recommandations de l'Insee**

* Pour importer des données de taille réduite (jusqu'à 1 Go), **il est recommandé d'utiliser les fonctions `read_csv()` et `read_delim()` du *package* `readr`**;
* Pour importer des données de taille plus importante (supérieure à 1 Go), **il est recommandé d'utiliser la fonction `fread()` du *package* `data.table`**.
* **L'usage du *package* `csvread` est déconseillé**, de même que l'utilisation des fonctions natives de `R` `read.csv()` et `read.delim()`.
:::
```

c'est-à-dire ajouter le flag `data-latex=""` par rapport à ce qui est fait jusqu'à présent. Un premier test avec a4d3cdc046d959d8008d9c6082a0e61f1107e2ef avec des box qui ne correspondent pas aux couleurs définies dans le `css`.

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Mar 18, 2020, 13:14

mentioned in merge request !10

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Mar 18, 2020, 13:44

0861fe2c7fb98ca4f462ec0a1cf8a4d4da4145e0 modifie la fiche d'exemple et bf90da540bd33f45b181c5b117698c789b4c18da définit des couleurs pour coller au `css`

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Mar 18, 2020, 14:09

@oliviermeslin le résultat est consultable [là](https://gitlab.com/linogaliana/documentationR/-/jobs/476305066/artifacts/download)

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Mar 18, 2020, 15:59

Merci @linogaliana . Je viens d'essayer désespérément de renvoyer à la ligne automatiquement les lignes trop longues dans le html et surtout dans le pdf, mais je n'y arrive pas. Je ne vois qu'une seule solution: appeler @RLesur à l'aide!

Romain: si tu regardes [là](https://gitlab.com/linogaliana/documentationR/-/jobs/476305066/artifacts/download), pages 32-33, il y a plusieurs lignes de code plus larges que `\textwidth`. Tu aurais une idée de comment on peut les découper automatiquement? J'ai trouvé [ce post](https://tex.stackexchange.com/questions/179926/pandoc-markdown-to-pdf-without-cutting-off-code-block-lines-that-are-too-long/412316#412316), mais je n'arrive pas à utiliser la configuration de `listings`.

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Mar 19, 2020, 08:18

@oliviermeslin , j'ai utilisé `listings` autrefois. A l'époque, j'avais créé un fichier listing.tex, qui ressemblait à ça (voir pj listing.tex). 

dans le doc principal, je chargeais le package listing (\usepackage{listings}), et dans les fichiers où il y en avait besoin, un petit \input{.path/vers/listing.tex} faisait l'affaire.

[listing.tex](/uploads/4372d1268e3a31226501bb355205ca71/listing.tex)

le résultat visible dans le doc part03_compiledCode.pdf

[part03_compiledCode.pdf](/uploads/e04f6f58654094a9cd1f4556d57d746d/part03_compiledCode.pdf)

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Mar 19, 2020, 08:33

Merci @gillesfidani, je vais voir si j'arrive à en faire quelque chose.

**Comment by linogaliana** [comment]
In GitLab by @RLesur on Mar 19, 2020, 10:04

@oliviermeslin alors là, comment dire... LaTeX et moi ne sommes plus trop amis. J'avais un peu expliqué les raisons [lors de ma participation au bookdown contest](https://rawgit.com/RLesur/pulpdown/gh-pages/pulpdown.pdf). À ta place, je ferais confiance à @gillesfidani :wink:

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Mar 19, 2020, 10:46

moi j'aime le latex ! :heart: 

oui, oui, je sais où se trouve la sortie --> []

je vais encore me prendre une relecture à cause de mes bêtises :cry:

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Mar 21, 2020, 08:32

Je viens d'accepter !10 pour les encadrés. Les autres chantiers feront l'objet d'une `MR̀` dédiée. Cela permet d'avancer par petit pas et ainsi d'avoir une idée plus claire de l'*output*  à mesure qu'on va accepter les `MR`  des fiches thématiques

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Mar 21, 2020, 09:55

Merci @linogaliana. Je suis d'accord avec toi. Il faut qu'on essaie de mettre certains chantiers derrière nous, sinon le dépôt va partir dans tous les sens.

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Mar 26, 2020, 09:53

mentioned in merge request !18

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Mar 31, 2020, 12:57

@all, j'ai réécrit quasi entièrement le préambule `LaTeX` dans la branche `latex`. Vu l'ampleur des modifs, j'ai conservé deux préambules: `preambule.tex` (identique à celui de la branche `master`) et `preambule_bis.tex` (proposition de mise en forme du pdf).

Vos commentaires et commits sont les bienvenus.

**Comment by linogaliana** [comment]
In GitLab by @mathias.andre on Mar 31, 2020, 13:31

Le pdf est vraiment très beau. Sauf erreur de ma part, il ne reste plus qu'à s'occuper d'un potentiel préambule et de la page de garde. @oliviermeslin : on ouvre un nouvel issue page de garde et on ferme celui-là ou tu préfères mener la discussion ici ?

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Mar 31, 2020, 13:37

Ici plutôt, ça évite d'avoir trop d'issues.

**Comment by linogaliana** [comment]
In GitLab by @mathias.andre on Mar 31, 2020, 14:20

OK. Donc les deux points essentiels à traiter pour la page de garde :
* le contenu
* l'aspect visuel

Selon moi, faisons léger. Il faut :  
- Insee et le logo 
- «UtilitR : Documentation R à l'usage des agents» (en titre et sous-titre)
- version X.Y - septembre 202Z (où Y, Y et Z changent chaque année)
- Document également disponible au format site : (le lien url où est le html)

Qu'en pensez-vous @all ? Une fois qu'on s'est accordé sur ça, je pourrais vous proposer une jolie page en LaTeX.

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Mar 31, 2020, 14:34

Ca me va. Claire voudra peut-être ajouter le logo du réseau LS2.

**Comment by linogaliana** [comment]
In GitLab by @mathias.andre on Jun 9, 2020, 16:53

Voilà une première proposition pour la page de garde du projet

![pageDocR](https://my-gitlab-bucket.s3.amazonaws.com/319657746/0c7a40bc39a4afd9f5c8245dcc98568a.png)

Maîtrisant plus LaTeX que Rmd, j'ai fait ça sur Overleaf. Code et accès au dépôt sur demande.

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Jun 9, 2020, 17:18

C'est super, merci @mathias.andre ! On devrait pouvoir l'intégrer au préambule LaTeX.

**Comment by oliviermeslin** [comment]
Je ferme car nous avons abandonné LaTeX suite à #207.
