### ISSUE TITLE
Faire une fiche sur l'importation de formats exotiques

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/utilitR#185]
J'ai l'idée de rédiger une fiche très courte sur l'importation en `R` de fichiers ayant un format inhabituel (dbf, par exemple).

Les principales recommandations pourraient être:
- Essayer de trouver les mêmes données dans un format courant (csv, SAS...);
- Essayer de convertir les données vers un format courant;
- Eventuellement, utiliser des _packages_ `R` spécifiques à ces formats (ceux utilisés par `rio` par exemple), mais __uniquement__ s'il est possible de sélectionner des lignes et des colonnes.

Qu'en pensez-vous?

**Comment by oliviermeslin** [comment]
Aurélien suggère d'ajouter dans `utilitR` quelque chose sur l'importation de données à largeur fixe. Je pense que ça peut prendre la forme d'une section dans la fiche sur l'importation de fichiers plats. On pourrait également mettre ça dans la fiche sur les formats exotiques.

**Comment by oliviermeslin** [comment]
Pour @linogaliana : un fichier à largeur fixe est une espère (rare mais pas éteinte) de fichiers plats, dans lesquels les colonnes ne sont pas délimitées, mais définies par leur position. Exemple: les 6 premiers caractères d'une ligne correspondent à la première colonne, les 3 suivants à la deuxième colonne, etc. 

Les données cadastrales disponibles à l'Insee sont structurées comme cela.

**Comment by linogaliana** [comment]
pas d'actu je ferme
