### ISSUE TITLE
RStudio (avec un S majuscule)

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/utilitR#187]
**Dans la catégorie "finitions" (aussi appelée "pinaillage") :**

RStudio est écrit dans la plupart des fiches avec un s minuscule. Il faudrait s'aligner sur la graphie "officielle" (S majuscule).

**Comment by oliviermeslin** [comment]
Merci @py-b. Grâce à toi `utilitR` vient de faire un grand pas en avant.

**Comment by py-b** [comment]
Y a aussi du mélange `UtilitR`/`utilitR` à quelques endroits (par exemple [Fiche_utiliser_utilitR.Rmd](https://github.com/InseeFrLab/utilitR/blob/fiche_utiliser_utilitr/01_R_Insee/Fiche_utiliser_utilitR.Rmd)).

**Comment by oliviermeslin** [comment]
Là c'est le grand bond en avant.

**Comment by linogaliana** [comment]
Je ferme cette *issue* car cette question est reprise dans #200
