### ISSUE TITLE
Licence du projet utilitR

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/utilitR#191]
Cette _issue_ est ouverte pour choisir la licence définitive d'`utilitR`. @RLesur a indiqué dans une réunion que le choix était vite fait, car il n'y en avait qu'une seule qui soit réellement adaptée. Le suspense est à son comble: quelle sera l'heureuse élue? Vous le saurez dans la prochaine contribution de @RLesur.

**Comment by RLesur** [comment]
En un lien <https://github.com/etalab/licence-ouverte/blob/master/LO.md>

**Comment by linogaliana** [comment]
Réglé par 5326b0c9e693a79741fe933bbcb083ae4ad83682
