### ISSUE TITLE
Choisir les polices

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/utilitR#197]
Cette _issue_ vise à définir les polices d'`utilitR`, tant pour la brochure pdf que pour le site. Deux éléments sur les critères de choix:
- Les polices doivent impérativement être sous licence libre, ce qui est assez contraignant;
- Nous pouvons utiliser des polices différentes dans les différents _outputs_ du projet (site, brochure pdf _via_ `pagedown`, pdf _via_ LaTeX);
- Les polices doivent être agréables à lire et à regarder.

Toute proposition est bienvenue!

**Comment by clairelegroux** [comment]
Je ne sais pas si ce sera si contraignant, tout dépend de la licence (ou des) cibles... (ex, la fameuse OpenSans est sous licence Apache)

Quelques questions :
- Quelle est la police utilisée pour le logo ?
- Quelle est la police actuellement utilisée pour le site ?

Pour faciliter la lecture il est préférable de ne pas utiliser trop de polices distinctes. En revanche il y a des familles ou séries de police, ce qui peut aider
Il faudrait cibler au moins :
- une police / famille de Police pour les titres (aux différents niveaux)
- Cibler une police pour le contenu
- Cibler une police pour le code

**Comment by oliviermeslin** [comment]
Réglé par #207
