### ISSUE TITLE
Fiche Utiliser R à l'Insee - Personnaliser R

### ISSUE THREAD

**Issue by acazaubiel** [InseeFrLab/utilitR#199]
Comment personnaliser sa configuration R et Rstudio?
 Il faut probablement distinguer les différents environnements. 
Parler du fichier .Rprofile, et dire ce qui peut être configuré.

**Comment by acazaubiel** [comment]
Juste pour être au clair, voici ce que j'aborde brièvement dans la fiche : 

1. Recommandation générale : la personnalisation de R est un outil intéressant, mais dangereux, car elle peut générer des pertes de reproductibilité. Il faut donc la réserver à des cas très précis et contrôlés : 

* Pour masquer des informations qui n'ont pas vocation à être publiques, comme des clé d'API ou des paramètres de proxy ;)
* Pour modifier des éléments sans importance sur les calculs, mais qui peuvent faciliter l'ergonomie de R (changement de prompt, de chiffres significatifs dans les digits, etc.)

2. Quelques éléments sur la manière dont R fonctionne au lancement, et la présence de deux fichiers importants, le .Rprofile et le .Renviron. 

3. Détails sur le .Renviron et la manière dont on le modifie via usethis::
4. Idem avec .Rprofile 

Recommandations finales : Il est ainsi fortement déconseillé de réaliser les choses suivantes (charger des packages ; définir des alias de fonctions ; modifier le comportement par défault, comme par exemple `options(stringAsFactors=FALSE)` dans le Rprofile).
Si vous faites de telles opérations spécifiques, alors : il faut travailler dans le .Rprofile d'un projet + partager le fichier `.Rprofile` du projet, après avoir vérifié qu'il ne contenait aucune information sensible.

Est-ce que ça convient ?

**Comment by linogaliana** [comment]
Oui je trouve que c'est un bon plan. 

Maes remarques mineures:

>    Recommandation générale : la personnalisation de R est un outil intéressant, mais dangereux, car elle peut générer des pertes de reproductibilité. Il faut donc la réserver à des cas très précis et contrôlés :

> * Pour masquer des informations qui n'ont pas vocation à être publiques, comme des clé d'API ou des paramètres de proxy ;)
> * Pour modifier des éléments sans importance sur les calculs, mais qui peuvent faciliter l'ergonomie de R (changement de prompt, de chiffres significatifs dans les digits, etc.)

Tout cela me convient bien. J'ajouterai le point : 

* Pour renseigner des variables d'environnement qui sont des chemins vers des exécutables sur lesquels s'appuient certaines librairies quand on n'a pas les droits administrateurs (et que donc celles-ci ne sont pas automatiquement ajoutées au `PATH`  de windows)


> Recommandations finales : Il est ainsi fortement déconseillé de réaliser les choses suivantes (charger des packages ; définir des alias de fonctions ; modifier le comportement par défault, comme par exemple options(stringAsFactors=FALSE) dans le Rprofile).
Si vous faites de telles opérations spécifiques, alors : il faut travailler dans le .Rprofile d'un projet + partager le fichier .Rprofile du projet, après avoir vérifié qu'il ne contenait aucune information sensible.

J'ajouterai  bien à ta remarque de ne pas partager le `.Rhistory` qui n'est pas un fichier de configuration mais d'historique de commandes où peuvent donc se retrouver des clés, mot de passe, etc.

**Comment by oliviermeslin** [comment]
J'avais pas vu cette _issue_, le contenu proposé me convient bien. J'aurai probablement plus de suggestions une fois que la premier jet sera écrit.

**Comment by linogaliana** [comment]
@oliviermeslin Il y a du contenu dans #201

**Comment by oliviermeslin** [comment]
Ah oui, je vais regarder!
