### ISSUE TITLE
remarques suite à relecture rapide du pdf

### ISSUE THREAD

**Issue by RLesur** [InseeFrLab/utilitR#208]
J'ai balayé très rapidement [cette version du document pdf](https://github.com/InseeFrLab/utilitR/runs/1736932010), voici quelques remarques : 

- [x] la numérotation des pages commence à 0 => mettre `counter-reset: page 1;` [ici](https://github.com/InseeFrLab/utilitR/blob/63af3f2528b7a4cda6d2dc5aea84fef4410a515a/css/default-page.css#L214) et [là](https://github.com/InseeFrLab/utilitR/blob/63af3f2528b7a4cda6d2dc5aea84fef4410a515a/css/default-page.css#L280)
- [x] p. 7 du pdf, [le logo génère un lien](https://github.com/InseeFrLab/utilitR/blob/63af3f2528b7a4cda6d2dc5aea84fef4410a515a/index.Rmd#L53) entre parenthèses
- [ ] les liens sont tous soulignés => utile à l'impression ? j'en doute
- [x] p.8 du pdf, remplacer [le lien relatif vers le manifeste](https://github.com/InseeFrLab/utilitR/blob/63af3f2528b7a4cda6d2dc5aea84fef4410a515a/index.Rmd#L119) et [celui vers le guide de contribution](https://github.com/InseeFrLab/utilitR/blob/63af3f2528b7a4cda6d2dc5aea84fef4410a515a/index.Rmd#L121) par des urls vers le repo github
- [x] problème de lien [ici](https://github.com/InseeFrLab/utilitR/blob/63af3f2528b7a4cda6d2dc5aea84fef4410a515a/01_R_Insee/Fiche_utiliser_utilitR.Rmd#L177)
- [x] l'idep [ici](https://github.com/InseeFrLab/utilitR/blob/63af3f2528b7a4cda6d2dc5aea84fef4410a515a/03_Fiches_thematiques/Fiche_import_fichiers_plats.Rmd#L155-L164) c'est pas glop (code non portable)
- [ ] des sorties de code débordent, quelques pistes : réduire le nombre de caractères de l'output de la console R (via une option knitr), rajouter [`pre {white-space: pre-wrap;}`](https://developer.mozilla.org/fr/docs/Web/CSS/white-space) dans le CSS media print et si besoin utiliser [`\u00ad`](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#suggesting_line_break_opportunities) dans les chemins tels que [ceux-ci](https://github.com/InseeFrLab/utilitR/blob/68ecc1613f61fd7228b5c49b253589584ac06058/03_Fiches_thematiques/Fiche_import_tableurs.Rmd#L23-L24)
- [ ] [ce tableau](https://github.com/InseeFrLab/utilitR/blob/fa4ebf0b95aff2059009e2d2aab2cf87cddd1348/03_Fiches_thematiques/Fiche_datatable.Rmd#L49-L98) part en vrac. On peut mettre un `id` pour le styler spécifiquement dans le CSS media print. Idem pour [celui-ci](https://github.com/InseeFrLab/utilitR/blob/fa4ebf0b95aff2059009e2d2aab2cf87cddd1348/03_Fiches_thematiques/Fiche_datatable.Rmd#L518-L546)
- [ ] bas de la p. 153 du pdf (numérotée 147) : forcer un `\pagebreak` pour éviter la coupure du code

**Comment by linogaliana** [comment]
on produit plus le pdf, je ferme
