### ISSUE TITLE
Faire une fiche sur l'importation de données à largeur fixe

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/utilitR#210]
Idée d'Aurélien. Ajouter une section dans la fiche sur l'importation de fichiers?

**Comment by linogaliana** [comment]
Face à cette *issue*, je me pose deux questions: 

1. C'est-à-dire ?
2. Ca ne rentre pas dans #185 ?

**Comment by oliviermeslin** [comment]
si en fait 😁
