### ISSUE TITLE
Réduire le volume du PDF

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#211]
Le problème non résolu par #207 est la volumétrie importante du PDF. Il est nécessaire de trouver une solution.

- [ ] Tester si `ghostscript` ne permet pas de résoudre cela

**Comment by oliviermeslin** [comment]
Il fait 14 Mo aux dernières nouvelles. Ca te semble toujours beaucoup trop?

**Comment by linogaliana** [comment]
Oui c'est trop. 14Mo Ça s'envoie pas par mail et ça prend sur notre limite de stockage des artefacts (je ne sais pas la limite github mais on en fait tourner pas mal et ils n'expirent pas immédiatement). 

Ceci dit, le problème est moins urgent que quand il faisait 40Mo donc la PR n'est pas prioritaire

**Comment by linogaliana** [comment]
on produit plus le pdf, je ferme
