### ISSUE TITLE
Packagisation du modèle de document

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#218]
Pour faciliter l'articulation entre les différents livres (à l'heure actuelle la documentation principale et le guide des Bonnes pratiques), le plus simple est de créer un modèle de document dans un package.

Ce n'est pas urgent mais c'est bien d'y penser avant la sortie de la V1

**Comment by oliviermeslin** [comment]
Ce serait mon premier _package_ 😀
