### ISSUE TITLE
[Fiches thématiques] Web sémantique - open data - ...

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#22]
In GitLab by @gillesfidani on Mar 19, 2020, 11:58

Proposition de plan (à revoir) :

# Le Web Semantique

### autres

# L'Insee et le WS

## Ressources

* [espace RDF Insee](https://www.insee.fr/fr/information/2410988)
* ...

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Mar 19, 2020, 12:03

merci @gillesfidani pour cette proposition. Deux petits points qui me viennent:

* Je ne sais pas du tout ce qu'est le Web sémantique;
* Avec ce plan, ne risque-t-on pas de s'éloigner de l'objectif qui est de faire une documentation succincte et centrée sur l'usage de `R`? Ceci dit, il est tout à fait possible (et à mon sens souhaitable) que les fiches de documentation (forcément un peu allusives) soient adossées à des tutoriels plus détaillés, donc ce plan pourrait être celui d'un tuto dont serait le rédacteur (veinard!).

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Mar 19, 2020, 12:44

>  les fiches de documentation (forcément un peu allusives) soient adossées à des tutoriels plus détaillés, donc ce plan pourrait être celui d'un tuto dont serait le rédacteur (veinard!).

Dont qui serait rédacteur ... ???

en fait, j'avais en tête plusieurs projets :

1. [Melodi]http://rdf.insee.fr/melodi/index.html

2. [Rmés]https://www.insee.fr/fr/information/4168396?sommaire=4168411

un guide pour communiquer avec les API de l'Insee *via* `R` ?

sous forme de tuto indépendant ou intégré à documentationr, je laisse les boss décider .

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Mar 19, 2020, 12:52

PS : https://github.com/FranckCo a une expérience **certaine** du sujet ...

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Mar 19, 2020, 13:51

Je corrige ma faute de frappe précédente: "dont tu serais le rédacteur (veinard!)."

C'est plus clair? :smile:

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Mar 19, 2020, 14:05

bien plus claiR !
reçu 7 / 7 @boss :smile:

**Comment by linogaliana** [comment]
In GitLab by @pierre-lamarche on Mar 19, 2020, 14:16

Ne pas oublier le package `RJSDMX` ; un outil cross-plateform et un vrai navigateur de séries ! À condition d'avoir la bonne version de Java.

**Comment by linogaliana** [comment]
In GitLab by @RLesur on Mar 19, 2020, 15:11

Je ne suis pas expert du sujet mais je m'y intéresse régulièrement. 

Pour consommer les données SMDX de l'Insee, j'ai utilisé à plusieurs reprises le package [{rsdmx}](https://github.com/opensdmx/rsdmx) (développé et maintenu par un :flag_fr:). Le provider Insee est intégré nativement. Donc, c'est pas très compliqué. En plus, le package est bien documenté. Dans son package perso, Alain a [une petite fonction utilitaire](https://github.com/AQLT/AQLTools/blob/master/R/dl_tools.R) qui l'utilise également.

Une partie de la communauté R utilise beaucoup le web sémantique, ce sont surtout les personnes qui bossent sur les questions environnementales (le web sémantique a l'air d'être très populaire dans ce domaine).  
On peut donc trouver, dans la communauté rOpenSci, Carl Boettiger ou Scott Chamberlain (il y en a d'autres) qui ont développé et maintiennent des packages dans ce domaine. J'ai un peu joué avec les packages [{redland}](https://github.com/ropensci/redland-bindings/tree/master/R/redland) et [{rdflib}](https://github.com/ropensci/rdflib) et j'ai beaucoup aimé.

Au niveau de la documentation, je vous recommande vivement la vignette du package {redland} écrite par Carl Boettiger :  
[_A tidyverse lover's intro to RDF_](https://docs.ropensci.org/rdflib/articles/rdf_intro.html).  
Je la trouve **exceptionnelle** de clarté. 

Sinon, au niveau de la communauté française, on peut signaler en géographie [Lise Vaudor](https://twitter.com/LVaudor), qui bosse à l'ENS Lyon, et travaille aussi sur le web sémantique. 

J'ai aussi vu une présentation d'utilisation de données du web sémantique en pharmaco-épidémiologie lors des Rencontres R 2018. C'était une présentation de Yann Rivault (basé à Rennes) : <https://r2018-rennes.sciencesconf.org/204778>. C'était très intéressant.

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Mar 19, 2020, 16:38

je pense que nous sommes plusieurs à utiliser `rsdmx`. J'aimerais bien avoir l'avis du COPS à ce sujet.

Un petit souci avec ce *package* : j'ai tenté sans succès de récupérer des données Eurostat *via* `rsdmx` **depuis un poste nomade Insee en télétravail**. Il faut configurer le proxy, et il semble y avoir un souci lié (de près ou de loin) à Direct Access et aux protocoles ipv4 / ipv6. Je n'ai pas très bien compris, mais @AureDisanto et Frédéric Conte pourraient peut être en dire +.

Je n'ai pas trop creusé, mais `rsdmx::readSDMX` utilise `RCurl::getURL` pour télécharger les données, et c'est la que le bât blesse (à vérifier).

@pierre-lamarche : `RJSDMX`, jamais utilisé. En général, j'essaie de rester loin du `Java`, notamment à cause du problème que tu soulèves.

@RLesur : idem, je ne suis pas du tout expert, mais je m'y intéresse régulièrement. Aucune expérience sur le rdf *via* `R` de mon côté. 

Un volontaire pour *piloter* la rédaction de ce tuto / fiche ? perso, je suis pas assez qualifié. Je veux bien contribuer par contre.

**Comment by linogaliana** [comment]
In GitLab by @RLesur on Mar 19, 2020, 16:50

@gillesfidani _a écrit_ :
> Je n'ai pas trop creusé, mais `rsdmx::readSDMX` utilise `RCurl::getURL` pour télécharger les données, et c'est la que le bât blesse (à vérifier).

Je pense que le mainteneur a l'air prêt à le faire contre rétribution ou bien qu'il serait prêt à accepter une pull request, cf. <https://github.com/opensdmx/rsdmx/issues/157>

**Comment by eblondel** [comment]
@linogaliana juste pour vous informer que la gestion des requêtes dans rsdmx a été changée (utilisation de httr au lieu de RCurl), ainsi que l'ajout d'un logger (INFO - simples messages R de rsdmx, ou DEBUG pour récupérer les logs curl). I s'agit d'une amélioration mineure contribuée sur du temps libre. Pour le reste, il y a de nombreuses perspectives de développements, mais qui nécessitent un effort significatif qui ne peut pas être fait sur du temps libre. De nombreuses organisations (nationales et internationales) utilisent rsdmx, mais à ce stade rsdmx n'a aucun sponsor. Sans un tel support, je suis contraint de faire une maintenance minimale du paquet, pour un maintien sur CRAN. Il serait intéressant de savoir si l'INSEE pourrait être motivé par le financement de certaines améliorations ou de nouvelles fonctionnalités, notamment pour suivre les évolutions de la norme SDMX.
