### ISSUE TITLE
Gérer à un seul endroit la liste des contributeurs

### ISSUE THREAD

**Issue by RLesur** [InseeFrLab/utilitR#220]
La liste des contributeurs est à deux endroits différents  : 

Dans le fichier `DESCRIPTION` 
https://github.com/InseeFrLab/utilitR/blob/236e8491d13fb4831a4e30a7ca106a4f6bbdbf47/DESCRIPTION#L8-L18

et dans le fichier `index.Rmd`
https://github.com/InseeFrLab/utilitR/blob/236e8491d13fb4831a4e30a7ca106a4f6bbdbf47/index.Rmd#L51-L63

C'est pas très carré et source d'erreur (elles sont différentes).

De mon point de vue, elle devrait être gérée dans le fichier `DESCRIPTION` seulement, elle peut alors être récupérée automatiquement comme ça par exemple : 

```r
format(Filter(function(x) !("cph" %in% x$role), desc::desc_get_authors()), include = c("given", "family"))
```

**Comment by py-b** [comment]
On pourrait de plus trier par `role`, pour faire figurer Lino et Olivier en pole position.

**Comment by oliviermeslin** [comment]
@RLesur: merci beaucoup. Réglé par f8478885b144075b

**Comment by RLesur** [comment]
attention @oliviermeslin , les deux listes n'étaient pas identiques, je pense que tu as fait disparaitre du monde (Lionel par exemple)

**Comment by oliviermeslin** [comment]
Damned

**Comment by py-b** [comment]
Lionel est ajouté, mais il a l'adresse mail de Claire. :stuck_out_tongue:

**Comment by oliviermeslin** [comment]
Pas facile de bosser avec un mainteneur aussi incompétent...
