### ISSUE TITLE
Fiche tidyverse: ajout de sous-section(s) sur la fonctionnarisation

### ISSUE THREAD

**Issue by acazaubiel** [InseeFrLab/utilitR#228]
La fiche data.table permet affiche notamment une sous-section sur la fonctionnarisation avec data.table.

Or, comme dplyr se repose sur de l'évaluation non standard, il est impossible de faire "aisément" de la fonctionnarisation.

Je proposerais volontiers une sous-section qui explique comment s'en sortir dans 80% des cas : 
- utiliser le {{colonne}} ;
- utiliser le `:=` permet de forcer l'évaluation à gauche notamment dans le mutate/summarize ;
-  éviter à tout prix le eval(parse(()) qui amène des pbs de performance + compréhension des messages d'erreurs + sécurité/robustesse via l'injection de code

Éventuellement, je peux essayer de construire une dernière section sur `purrr` (à voir si on ne veut pas l'intégrer dans une fiche spéciale du genre : Adieux aux boucles).

**Comment by acazaubiel** [comment]
@oliviermeslin  : tu peux m'y assigner avec comme échéance la fin de semaine prochaine.

**Comment by oliviermeslin** [comment]
@acazaubiel : merci beaucoup. Tu as raison, les deux fiches sont asymétriques. Toutefois, je me demande si ce n'est pas la fiche `data.table` qui va trop loin, car on avait dit que l'écriture de fonctions est hors `utilitR`. Il me semble que ce que tu décris aurais davantage sa place dans une fiche un peu avancée ""Ecrire des fonctions en `R`". Je pense que tu peux faire une PR sur le sujet dans tous les cas, et on va en discuter, au pire on déplacera les sections concernées vers une autre fiche. Ca te a?

Qu'en penses-tu @linogaliana ?

**Comment by linogaliana** [comment]
> @acazaubiel : merci beaucoup. Tu as raison, les deux fiches sont asymétriques. Toutefois, je me demande si ce n'est pas la fiche `data.table` qui va trop loin, car on avait dit que l'écriture de fonctions est hors `utilitR`. Il me semble que ce que tu décris aurais davantage sa place dans une fiche un peu avancée ""Ecrire des fonctions en `R`". Je pense que tu peux faire une PR sur le sujet dans tous les cas, et on va en discuter, au pire on déplacera les sections concernées vers une autre fiche. Ca te a?
> 
> Qu'en penses-tu @linogaliana ?

Je suis de l'avis d'Arthur. C'est un besoin classique de modulariser un code en mettant un argument de nom de variable. `dplyr` s'est amélioré dans le domaine, on peut évoquer ça. La documentation dplyr sur le sujet de l'évaluation non standard est indigeste, expliquer le principe simplement me semble faire sens (et renvoyer vers des ressources externes pour les éléments plus techniques). 

Ce qui est hors champ d'utilitR c'est la mécanique interne des fonctions (environnements, namespace...) pour lesquels on peut renvoyer vers le chapitre adéquat de la formation travail collaboratif.

**Comment by linogaliana** [comment]
A terme, on pourra faire une fiche spéciale ''ecrire des fonctions'' mais ça on avait repoussé à la V2

**Comment by oliviermeslin** [comment]
Donc tu es d'avis de laisser ça dans les fiches `tidyverse` et `data.table`, et pas d'isoler ça dans une fiche à part? C'est vrai que c'est moins de travail, parce qu'une fiche sur "Ecrire des fonctions" c'est un sacré morceau.
