### ISSUE TITLE
Boîte Insee

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/utilitR#234]
Créer un nouveau type de boîte pour mettre en exergue les particularités Insee.

Liste non exhaustives d'endroits où remplacer la boîte existante par ce nouveau type de boîte (ou créer une boîte) : 

- https://www.book.utilitr.org/comment-utiliser-la-documentation-utilitr.html#comment-installer-le-package-doremifasoldata
- https://www.book.utilitr.org/utiliser-des-packages-r.html#utilisation-de-la-fonction-install.packages
- https://www.book.utilitr.org/utiliser-des-packages-r.html#gestion-des-packages-avec-rstudio

Ne pas oublier de documenter cette boîte ici : https://www.book.utilitr.org/comment-utiliser-la-documentation-utilitr.html#contenu-des-fiches

**Comment by acazaubiel** [comment]
Complément à la liste non exhaustive : 

- https://www.book.utilitr.org/personnaliser-la-configuration-de-r.html#comprendre-le-lancement-de-r

**Comment by oliviermeslin** [comment]
Merci @py-b pour cette idée.

Voici une liste de noms de boîtes possibles :

- En pratique à l'Insee
- Pendant ce temps, à l'Insee
- Et à l'Insee ?
- Spécificités de l'Insee

J'ai une préférence pour "En pratique à l'Insee".

Je propose que la boîte utilise [l'icône maison](https://fontawesome.com/icons/home?style=solid).

**Comment by linogaliana** [comment]
L'icone maison me va bien (boite à mettre dans https://github.com/InseeFrLab/utilitr-template puisque j'ai mergé #229).

J'ai une préférence pour `Spécificités de l'Insee`. Je trouve que *"En pratique à l'Insee"* ne permet pas de comprendre l'objet de la boîte.

**Comment by CTassart** [comment]
En réponse à @oliviermeslin , ma préférence va également à "En pratique à l'Insee".
(Tu as raison, c'est mieux avec le lien de l'issue) ;)

**Comment by py-b** [comment]
Ok pour la maison.

Je rajoute des propositions :

- À l'Insee
- Particularité Insee
- Spécificités à l'Insee

Je préfère la 1re, et si comme Lino, vous trouvez que c'est trop vague, la 2e me semble être un bon compromis.
