### ISSUE TITLE
Faut-il aligner les couleurs sur la Charte Graphique de l'Insee ?

### ISSUE THREAD

**Issue by acazaubiel** [InseeFrLab/utilitR#235]
La charte graphique de l'Insee change régulièrement. La dernière version sur Agora que j'ai trouvé est [ici](https://www.agora.insee.fr/cms/sites/intranetddar/home/acces-par-unite/insee-info-service-iis/division-ecoute-et-communication/communication-externe-1/reseaux-sociaux-et-communication/la-charte-graphique-de-linsee-1.html).

On pourra notamment remarquer les couleurs des p.13 à 15.

* Faut-il essayer de s'aligner sur celles-ci ?
* Faut -il s'aligner sur le reste (Police, etc.)

**Comment by acazaubiel** [comment]
Avantages : 

* Insiste sur le lien avec notre institution
* accessibilité : _normalement_, les couleurs sont conçues pour être accessibles aux différentes formes de daltonisme (qui touche 8% des hommes et 0,5% des femmes dans le monde, pour rappel) :

Inconvénient : 

* Insiste sur le lien avec notre institution
* C'est pas compatible avec viridis ❤️

**Comment by linogaliana** [comment]
Pour les polices, je ne pense pas qu'on pourra s'aligner, on est assez contraint par la technologie utilisée.

Pour les couleurs des box, c'est plus envisageable.

**Comment by acazaubiel** [comment]
En fait, cette question de la charte graphique + couleurs rappelle plus largement qu'on est sensé fournir un service _accessible_, notamment auprès des personnes avec des problèmes de daltonisme (4% de la pop quand même -je n'arriverai jamais à me faire à cette stat !), mais il y a d'autres critères.
Sauf erreur de ma part, une unité de l'Insee se charger de regarder si les publications sont _accessibles_ et travaille sur le sujet.

**Comment by clairelegroux** [comment]
Bonjour
pour la vérification de l'accessibilité il faut passer par le réseau RANI, et particulièrement Isabelle Ravet qui le pilote.
La Charte Insee n'évolue pas tant que ça. Sa dernière mouture date de 2018. DEpuis quelques corrections mineures ont eu lieues (un peu à cause de moi) pour : 
implémenter les diaporamas correctement dans Impress (correction de certaines polices, modification, ou plutôt ajout de couleurs à la palette)
renforcer l'accessibilité des modèles, notamment pour les daltoniens, en modifiant les formes placées dans l'angle droit en bas des diaporamas selon chaque type de public (on ne se contente pas de la mention "modèle  jaune, rouge, bleu).

Pour avoir donc longuement travaillé avec les promoteurs de la Charte, dans l'esprit, la Charte se veut souple. Si l'on ne peut appliquer certains éléments, on ne les prend pas (ce qui répond à la question des polices pour nous).

Je vais rajouter le fichier des codes Hexa de la palette de couleurs Insee si vous voulez, mais j'ai un "petit" Bémol.

UtilitR est une doc initiée par des utilisateurs... du SSP (oui à la base d'abord l'Insee) et ne se veut pas interne ou limitative... Faut-il donc reprendre la Charte Insee ?

J'aurais plus tendance à chercher à créer une unité graphique avec le Logo UtilitR (en reprenant les couleurs du logo pour les couleurs à utiliser dans la doc par exemple...)

**Comment by linogaliana** [comment]
Je suis d'accord avec toi @clairelegroux qu'il vaut mieux privilégier l'identité graphique à partir des couleurs du logo. C'est ce qu'on a commencé à faire avec le nouveau thème et on va essayer de continuer dans cette direction.
