### ISSUE TITLE
Chapitre 1 : diminuer la taille des images "box"

### ISSUE THREAD

**Issue by acazaubiel** [InseeFrLab/utilitR#246]
Wow !

La taille des images "box" me semble gigantesque...

https://www.book.utilitr.org/presentation-utilitr.html#contenu-des-fiches

On doit pouvoir diviser par 4 la largeur des images, je pense...

Arthur

**Comment by oliviermeslin** [comment]
Merci @acazaubiel , je vais regarder

**Comment by oliviermeslin** [comment]
@acazaubiel : je pense avoir trouvé la solution.

**Comment by acazaubiel** [comment]
T'as résolu le pb des images... mais pas celui du tableau qui reste chelou avec une colonne centrale bcp trop large, non ?

**Comment by oliviermeslin** [comment]
@acazaubiel: oui, @linogaliana et moi cherchons la solution, on a pas encore trouvé.

**Comment by oliviermeslin** [comment]
@acazaubiel : réglé par fa070a4
