### ISSUE TITLE
Comment présenter l'infrastructure informatique de l'Insee

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/utilitR#250]
La rédaction des fiches sur l'environnement informatique de l'Insee (en particulier les fiches config et usage de Git, AUSv3 et SSP Cloud) pose un certain nombre de questions. J'en vois deux:

- spécificité: les fiches doivent-elles être assez générales (configurer Git en général), ou adaptées à l'usage de `R` à l'Insee (configurer Git pour s'en servir sur AUS et le SSP Cloud)?
- sécurité informatique: quelles informations pouvons-nous mentionner (adresse des ressources, nom des serveurs et des lecteurs, où mettre ses dépôts Git, où mettre sa clé SSH...).

Mon opinion sur les deux questions: 
- les fiches doivent être précisément adaptées à l'usage de `R` à l'Insee, mais les éléments spécifiques à l'Insee peuvent être isolées dans la boîte colorée "Spécificité Insee" (pour que les fiches soient faciles à réutiliser dans d'autres contextes). 
- Je ne sais pas quelles informations sont potentiellement sensibles. Je me demande si la bonne façon de procéder ne serait pas de rédiger les fiches concernées sur le Gitlab interne, de les faire valider par l'UNISSI, et de les remettre dans le dépôt principal.

Qu'en pensez-vous?

**Comment by gilles13** [comment]
> où mettre ses dépîts Git

acte manqué ?

1. y-a-t-il de grosses différences entre une config "générale" et une config adaptée à l'usage de R ? sinon oui, mieux vaut se focaliser sur les cas d'usage à l'Insee
2. aucune idée sur la question, mais la validation par l'UNISSI serait sécurisante

**Comment by oliviermeslin** [comment]
Je ferme cette _issue_ qui a déjà été discutée à la dernière réunion `utilitR`

**Comment by acazaubiel** [comment]
Pour rappel, le [CR](https://github.com/InseeFrLab/utilitR/wiki/CR_2021_20) de la réunion `utilitR` est là, n'est-ce pas ?
Je n'y vois pas le premier point, sur la "spécif" Insee... Qu'est-ce qui avait été décidé ? 
Pour ma part, je crois qu'il est *indispensable* de préciser la démarche pour pouvoir travailler en *package* depuis AUSv3 (donc, je partage ton avis Olivier). Je n'y arrive toujours pas, et je trouve ça très dommage ! 😞
