### ISSUE TITLE
Utilisation du token pour le protocole https sous Git

### ISSUE THREAD

**Issue by pierre-lamarche** [InseeFrLab/utilitR#255]
En lien avec la PR #219 
On a mentionné sur le canal de discussion interne l'absence de recommandations claires pour la configuration du token dans le cadre d'une communication en https avec les dépôts distants type Github et Gitlab ; la fiche explicite très bien comment générer ces tokens sous Gitlab, mais ne donne pas d'informations sur une éventuelle configuration des services RStudio/autres sur le SSP Cloud par exemple.
J'ai investigué le sujet et j'ai réussi à automatiser la configuration du token au démarrage du service (use-case : je veux lancer un service RStudio sur le SSPCloud qui se configure au démarrage pour que je puisse clôner mes dépôts sans rentrer mes identifiants, comme je ferais avec une clé SSH). Cela passe par l'utilisation des secrets du SSPCloud combiné à un script bash qui configure correctement l'authentification sous Git. Mais inclure un descriptif sur `utilitR`, c'est possible mais pénible : il faut détailler l'utilisation des secrets (ça c'est faisable) mais également du script d'initialisation (et là on arrive sur un profil d'utilisateur avancé). On peut imaginer qu'`utilitR` étende son champ d'action en mettant à disposition des scripts d'initialisation génériques et une procédure pour les utiliser (il faut prendre garde que les variables d'environnement utilisées par le script soient bien configurées par l'utilisateur dans ses secrets) ; mais avant de me lancer dans cette démarche fastidieuse, je préfère solliciter l'avis de la foule.

**Comment by milena-git** [comment]
Je suis pour perso côté use case!  -- mais @fcomte ne m'a pas encouragé à le faire

**Comment by fcomte** [comment]
disons que la sécurité c'est tjrs un arbitrage entre fonctionnalité et risque.
Je trouve ca un peu trop risqué (de mettre son token dans vault) par rapport à la facilité de faire git clone en début de session de travail. Néanmoins chacun est libre de s'exposer comme il l'entend :)

**Comment by oliviermeslin** [comment]
C'est une très bonne idée (ça me serait personnellement utile je pense), mais je pense qu'un tutoriel est trop avancé pour `utilitR`. En revanche, on peut le référencer, en mettant le lien. Qu'en pensent @RLesur et @linogaliana?

Où voudrais-tu le stocker ce tutoriel? Sur le Gitlab interne? Je me demande si mettre ce tutoriel en ligne sur internet est problématique en matière de sécurité.

**Comment by linogaliana** [comment]
On pourrait héberger (ou référencer) ce tuto (avec scripts) directement sur https://www.utilitr.org/. Il faut de toute manière qu'on réfléchisse à cette page d'accueil pour y mettre du contenu satellite à `utilitR`

Dans https://www.book.utilitr.org/, on ajoute un paragraphe ou une box qui signale l'existence de cette méthode pour le SSP-cloud. 

> Où voudrais-tu le stocker ce tutoriel? Sur le Gitlab interne? Je me demande si mettre ce tutoriel en ligne sur internet est problématique en matière de sécurité.

Cela n'a pas de raison d'être sur le Gitlab interne. Ce n'est pas plus problématique que la partie où on explique comment rentrer un token dans le *credential manager*

**Comment by RLesur** [comment]
Perso, je trouve l'idée de tuto très intéressante. 
Cependant, je me demande si, dans ce cas précis, on ne s'éloigne pas de la cible éditoriale initiale d'utilitR pour traiter un cas bien spécifique, à savoir l'utilisation du SSP Cloud.
Ce que je verrais bien dans utilitR, c'est expliquer que la plupart des packages de l'écosystème R s'appuient sur la variable d'environnement `GITHUB_PAT` et ne pas aller beaucoup plus loin.
Le use case proposé me semble plus coller avec des tutos d'utilisation du SSP Cloud.

Une suggestion pour partager le script de @pierre-lamarche : un gist ?

**Comment by linogaliana** [comment]
_outdated_ je ferme
