### ISSUE TITLE
Pb certificats sur https://www.pratiques.utilitr.org ?

### ISSUE THREAD

**Issue by acazaubiel** [InseeFrLab/utilitR#259]
J'ai eu une alerte de sécurité à cause d'un certificat non-valide sur le site "petit-frère" d'UtilitR.

Apparemment un certificat non valide, que j'ai pu _bypasser_ en faisant confiance au site.

Arthur

**Comment by linogaliana** [comment]
Merci @acazaubiel . Je vais profiter de la mise à jour du thème pour mettre à jour le certificat https. On verra si ça résout le problème. Tu y as accédé comment ? En cliquant sur un lien de la doc ou en tapant l'url depuis ton navigateur ?

**Comment by linogaliana** [comment]
@acazaubiel Le problème me semble réglé. Je ferme et on ouvrira à nouveau si besoin
