### ISSUE TITLE
Relecture des fiches

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/utilitR#260]
Bonjour à tous,

Voici l'_issue_ sur la relecture des supports. Le [CONTRIBUTING](https://github.com/InseeFrLab/utilitR/CONTRIBUTING.md) propose quelques astuces pour contribuer de manière simplifiée

## Méthode

L'idéal serait que chaque relecture se fasse dans une branche (et une PR vers `master`) dont le nom commencerait par `relecture_`. Lino et moi sommes disponibles pour aider ceux qui n'auraient pas l'expérience des _pull requests_.

## Répartition des fiches

Il suffit d'indiquer quelle fiche vous souhaitez relire, et je complèterai le tableau (ou vous pouvez l'éditer vous-même si vous savez le faire).

Fiche | Relecteur 1 | Relecteur 2
-- | -- | --
index | ? | ?
Fiche_utiliser_utilitR | ? | ?
Fiche_installer_packages | ? | ?
Fiche_comment_choisir_un_package | ? | ?
Fiche_utiliser_ressources | ? | ?
Fiche-personnaliser-R | @py-b  | ?
Fiche_configurer_git | @CTassart | ?
Fiche_git_utilisation | @CTassart | ?
Fiche_se_documenter | @gilles13 | ?
Fiche_demander_de_laide | @gilles13 | ?
Fiche_import_fichiers_plats | @acazaubiel  | ?
Fiche_import_tables_sas | @clerousset| ?
Fiche_import_tableurs | @faureME | ?
Fiche_connexion_bdd | @faureME | ?
Fiche_tidyverse | @milena-git | ?
Fiche_datatable | @milena-git | @clerousset
Fiche_joindre_donnees | ? | ?
Fiche_donnees_textuelles | ? | ?
Fiche_survey | ? | ?
Fiche_donnees_spatiales | ? | ?
Fiche_analyse_de_donnees | ? | ?
Fiche_graphiques | @acazaubiel  | ?
Fiche_rmarkdown | @py-b  | ?

**Comment by acazaubiel** [comment]
Ok, je propose de prendre Fiche_graphiques et Fiche_import_fichiers_plats.

**Comment by linogaliana** [comment]
@oliviermeslin Il y a aussi le guide des bonnes pratiques (www.pratiques.utilitr.org). tu veux procéder comment sur celui-là ?

**Comment by py-b** [comment]
**Fiche-personnaliser-R** et **Fiche_rmarkdown** dans un premier temps pour moi

**Comment by gilles13** [comment]
Fiches "se documenter" et "demander de l'aide" pour moi

**Comment by CTassart** [comment]
Je relirai les fiches **`Fiche_git_utilisation`** et **`Fiche_configurer_git`** mais il faut que je mette au clair sur la procédure ([A priori, c'est décrit ici : faut que je commence par cette lecture !](https://github.com/InseeFrLab/utilitR/blob/master/CONTRIBUTING.md))

**Comment by FaureME** [comment]
Je pourrais relire les fiches Fiche_import_tableurs et Fiche_connexion_bdd.

**Comment by milena-git** [comment]
Je pourrais relire les fiches tidyverse et data.table

**Comment by clerousset** [comment]
moi je peux aussi faire data.table et import_table_sas pour commencer

**Comment by jdlom** [comment]
@RLesur  m'a informé que vous recherchiez des relecteurs, je veux bien contribuer. 

@oliviermeslin, @linogaliana Pour les PR, vous souhaitez une modification directement du .Rmd associé ? 

Je veux bien relire : `Fiche_donnees_textuelles` et `Fiche_donnees_spatiales`

**Comment by oliviermeslin** [comment]
Merci beaucoup de contribuer @jdlom ! Normalement la marche à suivre est détaillée dans le Contributing.md. N'hésite pas à nous poser des questions si quelque chose n'est pas clair.

**Comment by GaelleGenin** [comment]
Bjr,

Fiche_donnees_textuelles pour moi.

J'avais déjà relu "Fiche_joindre_donnees".

Une remarque sur l'import des données quelque soit le format : je recommanderais très vivement de systématiquement sélectionner les colonnes nécessaires à la lecture d'un gros fichier. On peut alors faire une requête sur toutes les lignes d'un gros fichier de 7 Go qui répond en 1-3 secondes (lecture comprise).

**Comment by jdlom** [comment]
Bonjour,
j'aurais qqs dispos la semaine prochaine. 
Je veux bien me positionner sur `Fiche_connexion_bdd ` et sur `Fiche_joindre_donnees`
A bientôt,

**Comment by RLesur** [comment]
Bonjour,

La fiche `Fiche_utiliser_ressources.Rmd` a été relue par Géraldine Rochambeau  
Voici son retour : 

> RAS, très intéressant

**Comment by linogaliana** [comment]
je ferme cette *issue* plus d'actu
