### ISSUE TITLE
[Relecture] Fiche "Utiliser des packages R"

### ISSUE THREAD

**Issue by RLesur** [InseeFrLab/utilitR#268]
_Relecture de la fiche "Utiliser des packages R" par Géraldine Rochambeau (SSM Justice)_ 

La fiche est très claire. Deux questions à la lecture : 

- Comment sait-on si  Rtools est déjà installé sous windows ?
- Doit-on utiliser `update.packages()` à la place de `install.packages()` ? dans quels cas doit-on utiliser l'une, l'autre ou les deux ?

**Comment by oliviermeslin** [comment]
Merci à Géraldine, ses commentaires ont été pris en compte.

**Comment by RLesur** [comment]
Après une nouvelle relecture, Géraldine m'a transmis une remarque supplémentaire que je trouve intéressante : 

> En lisant cette fiche je me suis dit qu’il y avait aussi des versions R (anciennes), qui ne permettaient pas d'installer le package que l’on souhaite, à moins de changer de version de R (ce qui est indépendant de la volonté du statisticien qui est obligé de travailler avec la version de R mise à disposition)

**Comment by py-b** [comment]
Si cette remarque doit être prise en compte, cela se fera certainement en lien avec ce paragraphe (qui parle plutôt de montée de version de R) :

> Les packages R sont spécifiques à la version de R avec laquelle ils ont été installés. Ainsi, un package installé avec la version 3.6 de R peut ne pas fonctionner avec les versions 3.5 ou 4.0.  Cette contrainte est notamment due au fait que certains packages ont besoin d’une version minimale de R pour fonctionner. La principale conséquence pratique de cette caractéristique est que vous devrez réinstaller les packages si vous modifiez la version de R que vous utilisez. Cette réinstallation ne présente généralement aucune difficulté technique, mais elle peut prendre du temps.
