### ISSUE TITLE
Programmation de l'évènement de lancement des 8 et 9 juin 2021

### ISSUE THREAD

**Issue by clairelegroux** [InseeFrLab/utilitR#279]
Bonjour 

en retour du groupe de travail de préparation vous trouverez une ébauche de programme pour l'évènement de lancement. A cette adresse https://codimd.beta.innovation.insee.eu/FCLV960CTMaFoelVTyWMrg#

Nous pourrons en reparler plus en détail lors de la réunion du 28/04. Vos remarques, et réflexions sont d'ores et déjà les bienvenues pour que nous puissions valider le programme lors de cette réunion.

Merci d'avance !

**Comment by gilles13** [comment]
Quelques idées / remarques :

  * j'aime bien l'idée de répartir équitablement la durée de l'évènement entre apprentissage et démarche collaborative.

  * je crains que l'idée de coding dojo, malgré tout son intérêt, présente des difficultés d'ordre organisationnel : préparation des exo, nécessité de fournir un poste à ceux qui viendraient en présentiel sans leur matériel, installer les *packages* nécessaires, ... (le tout sur une durée de 45 min). A cela, il faut rajouter la difficulté de suivre/aider les participants en distanciel 

  * pour la J2, certains agents risquent de n'avoir que peu (ou pas de tout) de connaissance de l'outillage Insee indispensable au travail collaboratif (ssp cloud, git, ...). Introduire toutes ces notions en 45 min me semble un véritable *challenge*, mais ce serait très intéressant.

**Comment by sylvainDaubree** [comment]
Globalement je trouve ça très chouette, quelques points en vrac : 

- j'aime beaucoup les thèmes annexes à distiller, notamment l'idée de présenter les différentes communautés autour de R...
- je n'ai jamais fait de coding dojo, je suis d'accord que techniquement ça peut être assez compliqué en présentiel, à l'inverse, est-ce que ce n'est pas quelque chose qui se prête assez bien au distanciel (j'imagine que ce sera la plupart des gens ?) ? tout le monde est déjà sur son pc, l'installation de package va assez vite (d'autant qu'on doit pouvoir s'en tenir à des trucs assez basiques, genre tidyverse). Par contre ce n'est peut-être pas quelque chose de facile à organiser en _mixte_
- je trouve très bien la j2 avec ses deux options : une pour ceux qui veulent mettre les mains dans le cambouis, et une pour ceux (ils sont nombreux) qui veulent juste comprendre comment ça marche mais ne sont pas prêts, au moins dans un premier temps, à aller plus loin.

**Comment by RLesur** [comment]
Un mini détail en ce qui me concerne : profiter de ce que vient de faire @pierre-lamarche, à savoir lancer l'environnement utilitR sur le SSP Cloud pour montrer qu'en 2-3 clics, on peut avoir toutes les dépendances qui vont bien. Fini le mal de tête.

**Comment by clairelegroux** [comment]
à l'issue de la réunion nous avons conclus que l'idée de coding dojo ou tout simplement d'un mode participatif demanderait un investissement en terme de préparation qui n'était pas compatible avec la finalisation de la doc elle-même sur la même période.
(cf proposition amendée du 28 avril)

Pour lancer la communication et les invitations à l'évènement il faut donc définir les fiches UtilitR (mardi 8/06), et les projets collaboratifs  (mercredi 09/06) qui seront présentés. 

J'ai donc créé une issue  spécifique #299 . Quand nous aurons fixé l'ensemble je vous indiquerais ici le programme définitif

**Comment by clairelegroux** [comment]
Voici le programme final **à valider ce matin.**

### Les matinées de déconfinement d'UtilitR 8 et 9 juin 2021
#### Mardi 8 juin 2021: Apprendre avec la documentation UtilitR
**9h50** Accueil
**10h00** Plénière : 
* Présentation d'UtilitR (contenu, apports)
* UtilitR dans l'ensemble des ressources d'apprentissage

**10h50** Répartition en ateliers
**11h00** Ateliers : la documentation mise en pratique
**11h50** Retour en plénière
**12h00** Conclusion de la 1ère matinée et... surprise !

#### Mercredi 9 juin 2021: Collaborer et développer
**9h50** Accueil
**10h00** Plénière :  Présentation de la démarche collaborative d'UtilitR
- Apports et limites
- Système des sponsors

**10h30** Répartition en ateliers
**10h40** Ateliers  :Présentation de démarches et outils collaboratifs
**11h20** Retour en plénière
**11h30** Expérimentation de refonte d’un processus éditorial collaboratif : la note de conjoncture avec un gitflow
**12h00** Conclusion de la 2e matinée  et... perspectives 

_NB je n'avais pas retenu que le partie sur la conj était en plénière, on peut conserver tel quel ou prévoir un temps d'atelier plus long avec un atelier sur la conj_

**Comment by clairelegroux** [comment]
Avez-vous pu **valider** cette programmation ?

**Comment by RLesur** [comment]
Pour clôturer la matinée du 9 juin, on peut avoir une présentation de PROPRE. C'est très très proche, c'est aussi dans le SSP.

**Comment by linogaliana** [comment]
proposition dans #299

**Comment by clairelegroux** [comment]
**je considère le programme validé** en prenant en compte la programmation décrite pour me 9/06 dans #299

**Comment by linogaliana** [comment]
cet événement étant terminé 😫, on peut fermer l'issue
