### ISSUE TITLE
Choisir les goodies à commander

### ISSUE THREAD

**Issue by clairelegroux** [InseeFrLab/utilitR#280]
Bonjour 

dans le cadre de l'évènement de lancement, nous avons prévu la réalisation de Goodies.
- Des contacts ont été pris avec la Com Externe de l'Insee (pour le moment sans réponse) => si je n'ai pas de retour après une relance, nous ferons sans.
- Arnaud a pu faire confirmer la faisabilité financière 

Il faudrait désormais se déterminer sur les goodies que nous réaliserons. Sachant que certains objets sont bien évidemment moins couteux que d'autres.
Pour l'évènement, 2 goodies différents nous permettraient de marquer la participation à chaque matinée.
Un 3e pourrait être un bonus pour faire le lien entre les différentes parties Funcamp et les fiches UtilitR. Mais nous pourrions aussi utiliser les goodies Funcamp déjà disponibles (cf proposition de programmme dans l'issue #279 

On avait déjà commencé le brainstorming sur le sujet mais je n'ai pas retrouvé l'issue.
De mémoire on avait déjà parlé de
- Bloc notes
- crayon
- tasse (j'ai un petit doute sur le cout, peut être le must pour les contributeurs UtilitR)

Bref, à vos propositions... Bien sur, on choisit des goodies non périssables.

**Comment by clairelegroux** [comment]
J'ai pu demander à une collègue du DPII qui a déjà fait faire des Goodies.
Sur les conseils de la Com, ils étaient passés par https://www.dfccom.com/ 
(coté idée il y a de quoi faire...)

**Comment by oliviermeslin** [comment]
Merci @clairelegroux pour l'_issue_. Je pense que les objets suivants feraient de bons goodies :

- des tasses avec le logo. On peut en commander uniquement pour l'équipe de contributeurs (environ 30) pour réduire le coût.
- des autocollants avec le logo hexagonal. Ca ne doit être cher.
- des bloc-notes avec le logo, format A4 ou A5.
- des tapis de souris (si pas trop chers).
- je suis moins convaincu par les stylos, mais pourquoi pas.

**Comment by sylvainDaubree** [comment]
J'aime bien l'idée des tasses et des stickers hexagonaux, sur le reste je suis moins convaincu :
- les tapis de souris je n'en vois plus trop ? mais si c'est juste un biais personnel pourquoi pas !
- les blocs notes j'ai l'impression que les gens sont contents d'avoir plutôt leur cahier, je pense que ça va traîner au fond d'un placard et n'apporter ni utilité ni visibilité
- les stylos c'est dur de faire quelque chose de visible dessus

J'avais pensé sinon à une clé USB avec une version hors ligne, mais bof bof quand même.

**Comment by CTassart** [comment]
Je suis plutôt favorable aux mugs, stickers hexagonaux et blocs-notes.
Éventuellement une sacoche de transport (ce n'est pas moi qui gère le budget alors je me permets)

**Comment by linogaliana** [comment]
Mon opinion :

* mugs pour les contributeurs, plein de stickers : parfait
* bloc notes, stylo: bof. Je suis d'accord avec les arguments de @sylvainDaubree
* tapis de souris: pas trop d'avis.  
* 😷 utilitr ?

**Comment by gilles13** [comment]
idem, favorable aux mugs + stickers. Pour le reste, en fonction des moyens. Les tapis de souris sont peut être plus durables que les blocs notes et les stylos, mais pas d'avis tranché sur la question.

**Comment by GaelleGenin** [comment]
Un mug, pourquoi pas. On n'en a pas de personalisés Insee chez nous (en DG il me semble en avoir vus).
Et clé USB, c'est toujours utile.
Un forfait entretien chez Euromaster, ça peut être sympa aussi.

**Comment by clairelegroux** [comment]
dans les goodies réalisés par le "projet PEA") il y avait
tapis de souris
balle anti stress et 
un "collier" (je sais plus comment ça s'appelle)

**Comment by clairelegroux** [comment]
Bonjour
lors de la réunion du 25/04, nous nous sommes arrêtés à la réalisation de mug pour les gros contributeurs et de stickers.
_Le site que je vous ai donné au départ, ne propose pas de stickers, on va donc aller voir ailleurs !!_

**Pour le [mug](https://www.bureau-des-goodies.fr/produit/gobelets-reutilisables-personnalises-copi11)** 
(sachant qu'il peut y avoir des modèles sur fond bleu marine, mais je ne suis pas sûre de l'effet du logo sur ce bleu là...)
=> Forcément le prix est dégressif, mais je pense qu'on est dans une fourchette de prix tout à fait raisonnable pour faire faire quelques dizaines de mug

**Pour les [stickers](https://www.bureau-des-goodies.fr/categorie-produit/stickers)**
on peut ne faire qu'un seul type de sticker et dans ce cas choisir le modèle "à la découpe" pour avoir un sticker à la forme du logo

on peut aussi choisir plusieurs types de stickers (2 ou 3), en ajoutant un "**_message d'accroche_**" (ça se prête à l'évènement avec la remise de plusieurs goodies selon chaque matinée).
Dans la même idée, on peut peut être aussi ajouter un message d'accroche sur le mug.


### Questions à trancher 
#### 1.  Voulez vous ajouter un message d'accroche sur un ou plusieurs goodies ? _par principe, je considère que dans tous les cas, il nous faut au moins un modèle de sticker sans message (juste le logo)_

#### 2.  Si l'on choisit un message d'accroche, avez vous une ou plusieurs préférences parmi


1. Pour le Mug
 a. Top Contrib
 b. Proud Contributor 
 c. Je participe ! 
 d. (si ça ne change pas grand chose au prix, on pourrait penser à un mug "sponsors" : je soutiens)
 e. Vos propositions

2. Pour les stickers
 a. [UtilitR] Proud Contributor (cf [exemple](https://blog.documentfoundation.org/wp-content/uploads/2017/04/month_of_libreoffice_printed_sticker.png) )
 b. Besoin d'aide ? [UtilitR]
 c. [UtilitR] Ma référence !
 d. Vos propositions

En fonction de vos réponses, je ferais établir les devis. Dans l'idéal, si j'ai des réponses pour le 8 mai, on est dans les clous !

Merci !

**Comment by gilles13** [comment]
je pense que le choix sera dicté par le tarif. Je suppose qu'au plus on ajoute de déclinaisons, au plus ça chiffre ?!

pour Lino et Olivier, je vois bien "BDFL" (https://fr.wikipedia.org/wiki/Benevolent_Dictator_for_Life). Pour eux, ce sera "Bienveillant" dictators for life ;)

Si c'est *no limit*, je propose :

  * pour les sponsors : généreux sponsoRs ! ou généReux donateuRs !
  * pour la *core team* (je reprends les mots d'Arnaud) : meRci !, *core team*,  ...
  * pour les autres : utilitR (tout court)

Sinon, comme dit Sylvain, une version standard pour tous, c'est très bien

**Comment by py-b** [comment]
Pas un _goodie_ en tant que tel, mais on pourrait aussi imprimer des petites affiches de pub pour utilitR (A4 ou plus grand), à placarder aux endroits prévus à cet effet dans les établissements.

Sur le même principe, des petits dépliants que le public pourrait emporter.

À voir si on fait ça de manière artisanale ou par un professionnel.

**Comment by clairelegroux** [comment]
> 
> 
> Pas un _goodie_ en tant que tel, mais on pourrait aussi imprimer des petites affiches de pub pour utilitR (A4 ou plus grand), à placarder aux endroits prévus à cet effet dans les établissements.
> 
> Sur le même principe, des petits dépliants que le public pourrait emporter.
> 
> À voir si on fait ça de manière artisanale ou par un professionnel.
> 
> edit : je parle d'affiches ou de dépliants sur `utilitR` lui-même, pas sur l'évènement de lancement.

c'est pas bête, plutôt à prévoir quand on sortira l'édition papier en septembre ? (il y aura surement plus de gens dans le smurs Insee à ce moment là) 
Je ne vois pas trop la value de faire faire des affiches en mode pro (sauf si c'est pour la stratégie de com, mais je doute qu'on en soit là).

Bon pour le moment, le goodie "basique" vous convient, même si je note qu'il n'y a pas de franche opposition à autre chose, sauf si ça devait couter plus cher (non, ça ne devrait pas...). Comme indiqué précédemment, le goodies basique ets de toute façon incontournable, le tout est de savoir si on ne fait "que" du basique ou si ça vous tente de varier un peu...

**Comment by oliviermeslin** [comment]
Je suis favorable à des choses simples, comme @sylvainDaubree : des _stickers_ hexagonaux avec le logo (et rien d'autre); des mugs avec le logo (et rien d'autre). En revanche, je pense que nous pouvons choisir des mugs qui aient une jolie forme, tel que [celui-ci](https://www.avecvotrelogo.fr/250-ml-tasse-conique-brenta).

**Comment by linogaliana** [comment]
Je suis d'accord avec @oliviermeslin et @sylvainDaubree. J'ai une préférence pour n'avoir que le logo

**Comment by clairelegroux** [comment]
@oliviermeslin merci pour ce nouveau lien. Ils ne proposent pas de sticker sur ce site... 

Les devis vont être établis selon les règles suivantes
30 à 50 mugs (avec une "jolie forme" si possible) avec le logo (et rien d'autres)
300 à 500 stickers (si possible à la découpe = hexagonaux) avec le logo et rien d'autres.

**Comment by oliviermeslin** [comment]
Merci @clairelegroux , tu penses à nous montrer les différents mugs possibles avant de passer la commande? 🥺

**Comment by clairelegroux** [comment]
@oliviermeslin justement, je vous demande de choisir sur plusieurs modèles, et les devis, ce n'est pas une commande. 
Ne t'inquiètes pas. Je ne fige rien sans votre aval !!!

**Comment by clairelegroux** [comment]
Bonjour

pour avancer sur la commande des goodies.
Merci de valider/préciser les éléments suivants

### Réalisation des stickers avec le logo uniquement : 
**tailles souhaitées**
pour info, les stickers accolés sur PC font généralement entre 3 et 5 cm de coté....
vous pouvez choisir 2 tailles (le sticker sera le même, seule la taille changerait)

### Choix des mugs pour les contributeurs
**les critères de choix :** 
- possibilité d'imprimer le logo en couleur... (soit 3 couleurs)
- tenue du marquage au lave vaisselle (tout marquage de type tampographie est écarté)
[](url)
Je retiendrais les 3 choix les plus populaires (vous pouvez donc faire plusieurs choix)
[choix 1](https://www.igo-objetspub.fr/vaisselle/tasses/zonia-mug/p0686-master)
[choix 2](https://www.dfccom.com/products/4784/teamug.html)
[choix 3](https://www.igo-objetspub.fr/vaisselle/tasses/bigdrink-mug/p3685-master)
[choix 4](https://www.igo-objetspub.fr/vaisselle/tasses/palermo-mug/p1206-master)
[choix 5 - site 1](https://www.batelier.fr/fr/start-up/296-mug-vintage.html?search_query=mug&results=3) ou [choix 5 - site 2](https://camaloon.fr/mug-personnalise/mugs-vintage-en-ceramique-350-ml)
[choix 6](https://www.giftcampaign.fr/tasse-mug-publicitaire/mug-personnalise-pas-cher/tasse-promotionnelle-icon.html)
[choix 7 - site 1](https://www.giftcampaign.fr/tasse-mug-publicitaire/mug-personnalise-pas-cher/tasse-personnalisee-crescent.html) ou [choix 7 - site 2](https://www.laboiteaobjets.com/mug-publicitaire-sensa-160ml.html)

**Comment by gilles13** [comment]
beau boulot @clairelegroux 

par ordre de préf : 6, 1, 2, 4

**Comment by py-b** [comment]
5, 6, 1

**Comment by CTassart** [comment]
salut
1, 3, 7

**Comment by clairelegroux** [comment]
@sylvainDaubree 70 point pour le premier choix, 60 pour le 2e... etc le top 3 gagne.
(j'aurais fait 15 /10/5 à la base mais...)
je fais ça après avoir bouclé les annonces

@oliviermeslin la 7 est une tasse expresso... ;-)

**Comment by clairelegroux** [comment]
Les résultats du classement en rpenant en compte chaque réponse sont
Les points attribués étaient dégressifs selon le classement proposé, les points de chacun ont ensuite été cumulés pour chaque choix.
Choix 1
Choix 6
Choix 5 => au final pas de devis demandé, la méthode de marquage (tampographie) ne passant pas au lave vaisselle.

A l'issue, le devis du Choix 1 nous coute 100€ de moins. C'est donc lui le [https://www.igo-objetspub.fr/vaisselle/tasses/zonia-mug/p0686-master](gagnant)

Pour les stickers
on aura 500 stickers de 36 mm * 43 mm
et 200 stickers 50 * 60 mm. 
brillants, revêtement pvc, découpés à la forme.
On passe par HelloPrint, qui s'avère moins cher que Camaloon,
