### ISSUE TITLE
with_def("commit")

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/utilitR#298]
Dans la fiche sur l'installation des packages, plusieurs `with_def("<mot>")` apparaissent dans [ce paragraphe](https://github.com/InseeFrLab/utilitR/blob/21ca661f8493e1a3939a9bb8c256ba1ff11c1292/01_R_Insee/Fiche_installer_packages.Rmd#L121).

De ce que je comprends, cela est censé faire apparaître une définition du mot, mais le rendu ne semble pas fonctionner.

**Comment by linogaliana** [comment]
@py-b j'ai l'impression que tu fais référence à un ancien commit (en effet il aurait fallu écrire `r with_def("commit")` pour que ça fonctionne. Je ne le vois plus dans la version `master`. Je ferme l'*issue*, on la réouvre si jamais il y a encore des `with_def` non exécutés qui trainent

**Comment by py-b** [comment]
Je me suis peut-être mélangé les pinceaux avec les branches. En tout cas, ces with_def non évalués apparaissent sur le site :
https://www.book.utilitr.org/utiliser-packages.html#installation-avanc%C3%A9e
