### ISSUE TITLE
Lister les présentations du 8 juin (Fiches UtilitR)  et du 9 juin (sessions axées collaboratif)

### ISSUE THREAD

**Issue by clairelegroux** [InseeFrLab/utilitR#299]
* La 1ère journée de l'évènement de lancement a pour focale l'apprentissage via UtilitR
* La 2e journée de l'évènement de lancement a pour focale le développement de démarches collaboratives

## L'objet de cette issue est de déterminer de façon la plus certaine possible les sessions qui seront proposées.

- Présentation d'une fiche UtilitR ou d'une démarche collaborative
- durée estimée 50 min
- Au moins un animateur (qui est certain d'être disponible ! si souci à la dernière minute, on fera au mieux...)

### Résumé des propositions, les interventions **ne sont pas** validées !

|Focale |Thème | Animateur(s)/Animatrice(s) | Public ciblé * | Besoin particulier pour cette session |
|-----------|-----------|:---------:|:---------:|---------:|
|UtilitR |Rédiger en R Markdown|@RLesur (@gilles13 en co-animateur ou remplaçant)|Débutant|||
|UtilitR |Utiliser des _packages_, choisir ses _packages_, gérer ses dépendances|@RLesur||||
|UtilitR |data.table|@linogaliana (@gilles13 en co-animateur ou remplaçant)||||
|UtilitR |importer des fichiers plats / tableurs|||||
|UtilitR |utiliser le tidyverse|@acazaubiel||||
|UtilitR |faire des graphiques|@oliviermeslin|Debutant|||
|UtilitR |session BDD (à préciser)| @pierre-lamarche ||||
|Collab| Expérience modules d'auto-formation Grand Est|@py-b|||
|Collab| Premiers pas avec git|Annie|||
|Collab| Expérience de la conj ?|??|||

\*  *bien que la cible soit naturellement "les personnes qui ont besoin de creuser le sujet traité", je vous propose de renseigner cette colonne pour que l'on soit vigilant à ce que toute personne intéressée puisse trouver un sujet à sa portée, même s'il s'agît de neophytes...*

Pour rappel sur les démarches collaboratives nous avions évoqué : 

- Installer et outiller un cadre de collaboration sous R : premiers réflexes
- Monter une communauté de compétences R (témoignage) Sommer nos communautés ? Témoignage d’une communauté locale + Spyrales ?
- Présentation de la démarche de la Conj...
- L’Open Source, une façon d’apprendre à collaborer (qui n’est pas réservé aux geeks !)

**c'est à vous ! Un immense merci aux volontaires !**

**Comment by py-b** [comment]
**_Je recopie le mail que j'ai envoyé à l'issue de la réunion de la semaine dernière._**

En rapport avec la partie "Collaboration" du 2e jour, je porte à votre connaissance une initiative née au début du premier confinement :

Avec 2 collègues de Strasbourg, nous avons conçu des modules d'auto-formation accompagnée à R pour les agents du Grand Est :
- les stagiaires reçoivent un support en ligne contenant une séquence de cours et  des exercices. Ils ont environ une semaine pour le réaliser (pendant ce temps les formateurs restent à disposition pour toute difficulté) ;
- une séance de débrief collectif (environ 1h) ponctue chaque séquence.

Les supports ont été conçus à l'aide de **Rmarkdown + git + gitlab**. Le dépôt est sur mon compte personnel gitlab, pour être accessible depuis un poste personnel (une contrainte forte au printemps dernier) :
https://gitlab.com/py_b/formation-r-insee-grand-est/
À noter que mes 2 collègues ne connaissaient ni git ni gitlab au début du projet.

Deux modules ont été dispensés au premier 2020, et comme l'accueil a été très favorable, un nouveau module "Programmer avec R" va être lancé courant mai.

Si cela vous paraît pertinent, ceci pourrait figurer dans les exemples au côté de l'expérimentation sur la note de conjoncture.

ps: (ne pas diffuser ce lien, car nous diffusons en général les liens vers les séquences au fur et à mesure)

**Comment by RLesur** [comment]
Pour le 08/06, je peux animer une session au choix sur : 
- R Markdown
- choisir ses packages
- gérer ses dépendances

**Comment by linogaliana** [comment]
Pour le 08/06, je peux animer une session au choix sur :

* data.table
* git (les deux fiches)

**Comment by clairelegroux** [comment]
@RLesur faut voir s'il y a d'autres propositions qui se croisent... tous les thèmes sont porteurs, à première vue j'aurais voté pour R Markdown, mais c'est vous qui voyez

@linogaliana  pour git, on était plus dans l'idée de faire une "prise en main"/démarrage le 9. Mais c'est Annie qui avait ça en tête. Peut être que vous pouvez faire quelque chose de complémentaire ?

**Comment by linogaliana** [comment]
@claire oui tu as raison, j'avais oublié la présentation du 09 d'Annie. Dans ce cas, se concentrer sur les fiches R le 08 c'est mieux

**Comment by gilles13** [comment]
je me propose d'être animateur remplaçant (ou co-animateur) en cas de souci, sur les fiches Rmarkdown + data.table

**Comment by oliviermeslin** [comment]
Je pense qu'il est important, sur le côté fiches thématiques, de présenter les fiches basiques qui parleront au plus grand nombre, plutôt que des choses avancées. Je pense en particulier à :

- importer des fichiers plats ;
- importer des tables SAS ;
- utiliser le tidyverse ;
- faire des graphiques ;
- 

Je peux m'occuper de la fiche graphiques. Je propose demain une liste des fiches qu'on pourrait présenter.

**Comment by oliviermeslin** [comment]
Je vous propose que les sessions parallèles de la première journée portent sur les fiches suivantes :

- importer des fichiers plats/tableurs ;
- utiliser le `tidyverse` ;
- faire des graphiques ;
- rédiger en R Markdown ;
- choisir ses _packages_ et gérer ses dépendances (ça me semble faisable en une seule session) ;
- éventuellement utiliser `data.table`.

C'est à dessein que je laisse les tables SAS de côté (compliqué à présenter depuis le SSP Cloud).

Est-ce que cela vous convient? Si oui, on passe à la répartition des sessions.

**Comment by gilles13** [comment]
j'aurais préféré :

  * utiliser `data.table`
  * éventuellement, utiliser `tidyverse`

Puisque la démarche du projet est originale, autant aller jusqu'au bout, et présenter un *package* moins connu mais tout aussi puissant pour la manip de donnée.

Mais je pense que cette opinion ne sera pas très partagée, donc oui, tidyverse ... et oui, on laisse tomber la lecture de fichiers SAS.

**Comment by linogaliana** [comment]
@oliviermeslin Je pense qu'il est important de présenter `data.table` pour plusieurs raisons:

* dissiper le mythe que c'est uniquement pour de grosses données
* montrer que la syntaxe a une certaine logique mais que quand on l'a comprise, c'est pas plus compliqué que le tidyverse
* comme on a aucune formation en interne à data.table c'est bien de faire du prosélytisme pour le package

**Comment by py-b** [comment]
Le débat sur data.table renvoie peut-être à une question plus générale. Est-ce qu'on veut focaliser sur comment utiliser utilitR ou sur comment utiliser un package donné ?

Si c'est utiliser utititR, il faut éviter que le public arrive sans aucune connaissance sur le sujet (sinon il y aura deux choses à s'approprier en même temps). Par exemple, on pourrait orienter vers une présentation de data.table les agents connaissant déjà dplyr.

**Comment by oliviermeslin** [comment]
> Le débat sur data.table renvoie peut-être à une question plus générale. Est-ce qu'on veut focaliser sur comment utiliser utilitR ou sur comment utiliser un package donné ?
> 
> Si c'est utiliser `utilitR`, il faut éviter que le public arrive sans aucune connaissance sur le sujet (sinon il y aura deux choses à s'approprier en même temps). Par exemple, on pourrait orienter vers une présentation de data.table les agents connaissant déjà dplyr.

Mon point de vue: la session plénière sert à présenter l'utilisation d'`utilitR`, pour des agents sans aucune connaissance de `R`. Lino et moi avons préparé une présentation générale qui fait cela. Donc les sessions parallèles servent plutôt à donner l'occasion aux agents de mettre en pratique par eux-mêmes, dans le cas d'un _package_/d'une tâche qui les intéresse en particulier.

**Comment by pierre-lamarche** [comment]
Je sais qu'en disant ça, je me mets une corde au cou, mais je suis un peu ennuyé de ne pas voir de session consacrée à la communication avec les bases de données. `tidyverse` pourquoi pas, mais il y a peut-être des utilisateurs qui pourraient avoir envie de manipuler des données volumineuses, et au risque de me répéter, je n'ai pas le sentiment que `data.table` soit l'alpha et l'oméga sur ce sujet.

**Comment by linogaliana** [comment]
@pierre-lamarche je suis absolument d'accord avec toi.

Si la solution RP dans une BDD est fonctionnelle le 08/06 (c'est ça ta corde au cou ?), je pense que c'est un très bon sujet de fiche à présenter.

**Comment by clairelegroux** [comment]
si on a déjà 4 interventions pour chaque jour on est bons, on pourra compléter sans que ce soit bloquant pour lancer la comm.

Il faudrait donc aussi cibler les interventions du 09. A priori on a déjà (mais il nous faut les intervenants !)

* l'expérience dans la DR Grand Est @py-b (si tu me trouves un meilleur libellé)
> ce qui répond à "Monter une communauté de compétences R (témoignage) Sommer nos communautés ? Témoignage d’une communauté locale + Spyrales ?"
* premiers pas avec git (avec Annie ?)
* expérience de la conj 
* l'Open Source, une façon d’apprendre à collaborer (qui n’est pas réservé aux geeks !)

**Comment by oliviermeslin** [comment]
Je suis entièrement d'accord avec @pierre-lamarche et @linogaliana. Si on arrive à avoir une solution BDD qui fonctionne sur le SSP Cloud, il faut qu'on fasse une session BDD.

**Comment by clairelegroux** [comment]
j'ai fait un recap des différentes propositions dans le tableau du premier message...
Il faudra bien sur garder en tête qu'un même intervenant ne peut être pris qu'une fois (@linogaliana et @RLesur ont proposé le choix...)

**Comment by acazaubiel** [comment]
@oliviermeslin : je dois pouvoir faire le tidyverse. J'aime bien le tidyverse.  :)

**Comment by clairelegroux** [comment]
@py-b le propos de cette matinée c'est justement d'axer les interventions sur la "manière de" plus que sur le contenu lui-même produit (1ère matinée). 
l'angle principal que tu décris me parais du coup bien adapté.

**Comment by GaelleGenin** [comment]
Bjr,
je peux parler du tidyverse si besoin, ou sur l'import de fichiers plats, pour un public de débutants.

**Comment by oliviermeslin** [comment]
Merci @GaelleGenin. La difficulté est qu'il faut que les fichiers csv, xls, etc. utilisés dans la démonstration soient présents dans le SSP Cloud. On doit pouvoir trouver une solution, mais c'est pas immédiat. On va regarder ça.

@linogaliana : tu penses qu'on pourrait ajouter dans l'image Docker un dossier `data` qui contiendrait des fichiers de données, et auxquels on aurait accès depuis RStudio _via_ le _path_ `/data/monfichier.csv`?

**Comment by py-b** [comment]
> Merci @GaelleGenin. La difficulté est qu'il faut que les fichiers csv, xls, etc. utilisés dans la démonstration soient présents dans le SSP Cloud. On doit pouvoir trouver une solution, mais c'est pas immédiat. On va regarder ça.

Si le public ne participe pas, le présentateur peut aussi juste les avoir sur son poste. Une solution de secours si la solution technique basé sur le SSPCloud n'est pas opérationnelle.

**Comment by Claire** [comment]
> @Claire yes you're right, I forgot Annie's 09 presentation. In this case, focusing on non git files on 08 is better

wrong Claire :)

**Comment by clairelegroux** [comment]
au final, quels sont les ateliers **validés** ?

**Comment by oliviermeslin** [comment]
Voici la liste des présentations que je propose de retenir pour le 8 juin. Est-ce que cela vous convient?

Trois points importants :

- Personne n'est obligé d'animer une session, et on peut intervertir en fonction des préférences de chacun;
- Les contributeurs qui ne sont pas dans la liste (notamment @sylvainDaubree, @py-b , @gilles13) peuvent  évidemment se rajouter comme coanimateurs s'ils le souhaitent (ou animateur principal);
- Si vous acceptez d'animer une session, cela implique de vraiment bien la préparer: bien connaître les exemples, bien vérifier que tous les exemples fonctionnent, répéter la présentation...

|Focale |Thème | Animateur(s)/Animatrice(s) |
|-----------|-----------|:---------:|
|UtilitR |Importer des fichiers plats / tableurs| @GaelleGenin|
|UtilitR |Utiliser le tidyverse|@acazaubiel|
|UtilitR |Faire des graphiques|@oliviermeslin|
|UtilitR |Utiliser des _packages_, choisir ses _packages_, gérer ses dépendances|@RLesur|
|UtilitR |Utiliser `data.table` |@linogaliana|
|UtilitR |session BDD (sous réserve)| @pierre-lamarche |

**Comment by RLesur** [comment]
> Merci @GaelleGenin. La difficulté est qu'il faut que les fichiers csv, xls, etc. utilisés dans la démonstration soient présents dans le SSP Cloud. On doit pouvoir trouver une solution, mais c'est pas immédiat. On va regarder ça.
> 
> @linogaliana : tu penses qu'on pourrait ajouter dans l'image Docker un dossier `data` qui contiendrait des fichiers de données, et auxquels on aurait accès depuis RStudio _via_ le _path_ `/data/monfichier.csv`?

Ce n'est pas du tout standard (autrement dit pas du tout une bonne pratique) que de mettre des données dans une image docker. Il vaut mieux faire ça via le script init.

**Comment by oliviermeslin** [comment]
@RLesur : merci pour la précision. On peut pas trouver une solution avec `gtools` et `defmacro`?

**Comment by linogaliana** [comment]
Oui je suis d'accord avec @RLesur , il vaut mieux privilégier le script `init`

**Comment by linogaliana** [comment]
@oliviermeslin je suis ok sur le programme que tu proposes. Je mettrai seulement la séance import sous réserve (comme la fiche bdd) car il faut:

1. Trouver de bonnes données pour que ce soit intéressant
2. Trouver la solution technique adéquate (script init proposé par romain)

**Comment by clairelegroux** [comment]
C'est bien. Ça se précise.
Une proposition pour les présentations du 9 juin aussi ??

**Comment by oliviermeslin** [comment]
Voici une proposition pour le programme du 9 juin:

| Horaire   approx | Type de session |                                                | Animateur |
|------------------|-----------------|------------------------------------------------|-----------|
| 10h-10h30        | Plénière        | La démarche du projet `utilitR`                |     @linogaliana       |
| 10h40-11h10      | Parallèle 1     | R Collaboratif                                 |    Annie       |
| 11h15-11h45      | Parallèle 1     | Autoformation: l'expérience de la DR Grand Est |   @py-b         |
| 10h40-11h10      | Parallèle 2     | Rmd centre de crise covid Drees                | Drees          |
| 11h15-11h45      | Parallèle 2     | Retour d'expérience de la conj                 |  Conj         |
| 11h50-12h20      | Plénière        | La démarche PROPRE                             |  A préciser         |
| 12h20-12h30      | Plénière        | Conclusion: vers l'infini et au-delà           |  A préciser         |

**Comment by RLesur** [comment]
La présentation de la démarche PROPRE est confirmée. Seront présents : 
- Juliette Engelaere-Lefebvre (Dreal des Pays de la Loire)
- Maël Theulière (Dreal des Pays de la Loire)
- Sébastien Rochette (ThinkR)

Juliette et Maël présenteront et Sébastien sera là pour les QR

@oliviermeslin et @linogaliana sont en relation avec eux.

**Comment by RLesur** [comment]
La présentation de l'expérimentation menée au département de la conjoncture est confirmée. Seront présents : 
- Jules Baleyte (division synthèse conjoncturelle)
- David Fath (division synthèse conjoncturelle)

@oliviermeslin et @linogaliana sont en relation avec eux.

**Comment by clairelegroux** [comment]
J'aime quand ça avance comme ça !
c'est quoi PROPRE ?

Pour la dernière Plénière, on verra si Arnaud est ok....

Il nous faut donc 6 créneaux zoom pour le 8 et 2 pour le 9

**Comment by RLesur** [comment]
La démarche PROPRE (PROcessus de Publications REproductibles) est extrêmement proche de celle qui a été adoptée pour utilitR.
Voici un diapo de présentation https://rdes_dreal.gitlab.io/propre.presentation/presentation_spyrales.html
Quelques liens : 
- https://gitlab.com/rdes_dreal/propre.brochure/-/blob/master/export/demarchePropre.pdf
- https://rdes_dreal.gitlab.io/publication_guide/production/
- https://rtask.thinkr.fr/fr/organisation-collaboratif-publication-propre/

**Comment by clairelegroux** [comment]
Bonjour j'ai réservé (les horaires sont volontairement plus larges....)

**Pour le 8/06** 
- un créneau Plénière et Atelier import de fichiers plats et tableurs de 9h30 à 12h30
- un créneau Atelier Tidyverse de 10h à 12h
- un créneau Atelier Graphiques de 10h à 12h
- un créneau Atelier Packages et dépendances de 10h à 12h
- un créneau Atelier data.table de 10h à 12h

**Pour le 09/06**
- un créneau Plénière et Parallèle 1 de 9h45 à 13h
- un créneau Parallèle 2 de 10h à 12h
