### ISSUE TITLE
Gestion des numéros de version directement via le fichier DESCRIPTION

### ISSUE THREAD

**Issue by pierre-lamarche** [InseeFrLab/utilitR#301]
Dans la PR #300 on gère le numéro de version à la main, avec plusieurs manipulations à la main pour rendre les choses cohérentes.
Lors du CI sur github-action, l'idéal serait d'aller alimenter une variable d'environnement (par une expression régulière sur le fichier DESCRIPTION ?) afin de construire une image docker disposant d'un tag cohérent avec la version de la documentation. D'expérience sur `doremifasol`, le sujet est un peu pénible. 
SI certains d'entre vous ont une bonne maîtrise de Github Actions, je suis preneur de leurs lumières.

**Comment by py-b** [comment]
> par une expression régulière sur le fichier DESCRIPTION ?

Avec R, on peut en extraire des infos facilement :
```r
read.dcf("DESCRIPTION", fields = "Version")[1, ]
```

Tu cherches une commande équivalente en bash pour la CI ?

**Comment by pierre-lamarche** [comment]
On peut toujours faire du `Rscript` en bash, je vais tester, merci.

**Comment by linogaliana** [comment]
Réglé par #300
