### ISSUE TITLE
Pertinence d'une réserve sur la programmation avec dplyr ?

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFrLab/utilitR#321]
Bonjour

Dans la section [Définir des fonctions modifiant un data.table](https://www.book.utilitr.org/datatable.html#d%C3%A9finir-des-fonctions-modifiant-un-data.table), il y a un encadré apportant une réserve sur la programmation avec dplyr.

Cette réserve s'appuie ici sur la complexité (avérée à mon sens) de programmer en NSE, mais _avant_ la version 0.4.0 de rlang. La nouvelle syntaxe est d'ailleurs décrite [dans le chapitre 17](https://www.book.utilitr.org/tidyverse.html#programmer-des-fonctions-avec-le-tidyverse).

Est-ce qu'il faut adapter l'encadré à la nouvelle syntaxe et garder la réserve ? Ou bien faudrait-il le supprimer tout simplement ?

**Comment by linogaliana** [comment]
Bonjour @romaintailhurat, ta remarque est tout à fait fondée. La section à laquelle tu fais référence dans le chapitre 17 est toute neuve (elle date d'hier, merci @acazaubiel).

Je pense qu'on peut supprimer cette remarque. Je ne sais pas si les dernières évolutions de `rlang` rendent la programmation en NSE aussi simple qu'avec `data.table` mais ce n'est plus un cauchemar de programmer avec dplyr

**Comment by linogaliana** [comment]
done in b51effa90078836ba3ccd803701685da2ea72c97

**Comment by romaintailhurat** [comment]
Thanks
