### ISSUE TITLE
Favicon absente du bookdown

### ISSUE THREAD

**Issue by RLesur** [InseeFrLab/utilitR#323]
Le favicon a disparu de https://www.book.utilitr.org/

**Comment by oliviermeslin** [comment]
Flûte. Je sens que @linogaliana est surchaud pour résoudre ce truc.

**Comment by ddotta** [comment]
Apparemment, mettre un favicon dans un `bs4_book` [n'est pas encore possible](https://github.com/rstudio/bookdown/issues/1011) mais bon quand je vois le hack que vous avez utilisé pour mettre le hex d'utilitr dans le menu de gauche (pas prévu lui non plus 😄), rien d'impossible pour vous !
