### ISSUE TITLE
ajouts/commentaires fiche data.table

### ISSUE THREAD

**Issue by clerousset** [InseeFrLab/utilitR#327]
Après relecture de la fiche data.table, comme j'ai des propositions d'ajouts j'ouvre cette issue.

1) Au début sur l'affichage des data.table, je rajouterais bien un paragraphe conseil (je m'applique ce conseil personnellement et c'est très bien) :
::: {.conseil}
Modifier les options globales de `data.table` permet d'avoir un affichage encore un plus informatif avec les classes de chaque colonne et l'éventuel clé de la base (voir plus bas [Indexer une table avec `data.table`]) :
```{r}
options(
  "datatable.print.keys" = TRUE,
  "datatable.print.class" = TRUE
  )
dt
options(
  "datatable.print.keys" = FALSE,
  "datatable.print.class" = FALSE
  )
```
:::

2) Sur la syntaxe dt[i, j, by] je rajouterais bien aussi la remarque suivante (avantage fondamental de data.table sur dplyr/pandas):
::: {.remarque}
Cette syntaxe compacte est aussi un des atouts fondamental de `data.table` pour sa rapidité : au moment de faire le regroupement par `z`, il sait déjà qu'il n'aura que `y` à traiter et donc ne manipule pas les colonnes non concernées.
:::

3) Sur les fonctions statistiques de data.table
::: {.remarque}
A strictement parler `%in%` est du R base.
:::
::: {.remarque}
Quitte à ne pas mettre beaucoup de fonctions spécifiques `data.table`, je remplacerais bien `%between%` qui est une petite fonction par des fonctions plus "spéctaculaires" comme`nafill` ou `fcase`
:::

4) Sur la programmation avec data.table
::: {.remarque}
La version 1.14.1 de `data.table` (encore en développement au 13/05/2021) apporte une syntaxe améliorée dans ce cas et considère l'utilisation de `get` comme désuète. Le `[...]` admet un nouvel argument `env` à qui on donne tous les remplacements que l'on souhaite. L'exemple devient :
```{r, eval = FALSE}
creation_var <- function(data, nom_variable, nouveau_nom){
  data[, nouveau_nom := nom_variable + 1, 
    env = list(nouveau_nom = nouveau_nom, nom_variable = nom_variable)]
}
head(creation_var(filosofi_com_2016_dt, 
                  nom_variable = "NBMENFISC16",
                  nouveau_nom  = "nouvelle_variable"), 2)
```

L'avantage c'est qu'on peut effectuer de tels remplacements dans `i` et qu'on peut même remplacer des fonctions :
```{r, eval = FALSE}
creation_var <- function(data, nom_variable, nouveau_nom, fonction){
  data[, nouveau_nom := fonction(nom_variable), 
    env = list(nouveau_nom = nouveau_nom, nom_variable = nom_variable, fonction= fonction)]
  head(creation_var(filosofi_com_2016_dt, 
                  nom_variable = "NBMENFISC16",
                  nouveau_nom  = "nouvelle_variable",
                  fonction = "sqrt"), 2)
}
```
:::

5) Sinon j'aurais des choses à dire sur l'optimisation de data.table (GForce etc.) mais ça dépasse peut-être votre ligne éditoriale

**Comment by clerousset** [comment]
Plus une remarque importante il me semble sur .N :
::: {.remarque}
La fonction `.N` permet de créer facilement des compteurs avec la syntaxe `1:.N`. Par exemple `dt[ , compteur := 1:.N, by = 'group_var']`
:::

**Comment by oliviermeslin** [comment]
Merci @clerousset. Même réponse que dans l'autre _issue_: n'hésite pas à faire une PR vers la fiche `data.table` avec les modifications que tu proposes.
