### ISSUE TITLE
liens hypertexte difficilement visibles

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/utilitR#330]
Quelqu'un d'autre a aussi des difficultés à distinguer les hyperliens dans le texte ?

Changer la couleur pour les distinguer mieux du noir du texte principal ? Souligner ?

**Comment by linogaliana** [comment]
oui je suis d'accord avec toi @py-b 

Ils sont couleur #5b9595 d'après firefox. Un bleu-vert proche du noir donc. @oliviermeslin t'es ok pour changer la couleur ?

**Comment by oliviermeslin** [comment]
Oui, ça fait plusieurs fois que j'essaie de changer la couleur, et ça ne fonctionne pas. Je vais m'en occuper.

**Comment by oliviermeslin** [comment]
Normalement c'est réglé. @py-b : tu confirmes?

**Comment by py-b** [comment]
C'est parfait.
