### ISSUE TITLE
Recensement des ressources en français en licence ouverte

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#34]
In GitLab by @oliviermeslin on Apr 3, 2020, 13:01

Cette *issue* a pour but de recenser les ressources existants en français en licence ouverte, que nous pourrions réutiliser dans la documentation (en créditant les auteurs). Cette étape me semble un prérequis indispensable avant la rédaction des fiches sur des *packages* très courants (notamment `tidyr/dplyr` et `ggplot2`).

J'ai repéré deux sources de grande qualité à ce stade, n'hésitez pas à compléter.

| Source                                                                              | Licence                   | Champ couvert                                       |
|-------------------------------------------------------------------------------------|---------------------------|-----------------------------------------------------|
| [Introduction à `R` et au `tidyverse`](https://juba.github.io/tidyverse/index.html) | Creative Commons BY-NC-SA 4.0 | `dplyr`, `tidyr`, `ggplot2`, `stringr`, `rmarkdown` |
| [Introduction à `R` du MTES](https://mtes-mct.github.io/parcours-r/)                | Licence ouverte Etalab    | statdes, `dplyr`,  `ggplot2`, `kable`, `rmarkdown`               |
| [Formation de Martins sur `R`](https://teaching.slmc.fr/)                | Licence ouverte Etalab    | statdes, `R base`, `dplyr`,  `ggplot2`               | Creative Commons BY-NC-SA 3.0 FR

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Apr 3, 2020, 13:03

changed the description

**Comment by linogaliana** [comment]
In GitLab by @RLesur on Apr 3, 2020, 13:36

On a commis ça il y a quelques jours https://spyrales.netlify.com/blog/20200323-blog-ressources-r/

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Apr 3, 2020, 16:01

Effectivement...

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Apr 3, 2020, 17:02

changed the description

**Comment by linogaliana** [comment]
In GitLab by @pierre-lamarche on Apr 4, 2020, 13:22

C'est très *old school* mais quand j'ai voulu me mettre à R, il y avait ça en français : [https://cran.r-project.org/doc/contrib/Paradis-rdebuts_fr.pdf](https://cran.r-project.org/doc/contrib/Paradis-rdebuts_fr.pdf)

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Apr 4, 2020, 13:29

j'ai commencé en R avec ce doc. Génial, mais *old school* effectivement.

**Comment by oliviermeslin** [comment]
Je ferme cette _issue_, car nous avons décidé de ne pas reprendre de contenus provenant de ressources extérieurs pour des raisons de licence.
