### ISSUE TITLE
améliorer reproductibilité import fichiers

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/utilitR#343]
La plupart des exemples des fiches sur l'import de fichiers ne sont pas (facilement) reproductibles.

On pourrait peut-être utiliser `doremifasol` comme l'a fait @oliviermeslin [ici](https://github.com/InseeFrLab/utilitR/blob/6c9ae0767923ae9ea17c60174f640707f2c8c7f1/resources/fichiers_plats/scrit_init_fichiers_plats.R).

Je comprends bien qu'on approche de la date butoir de finalisation, donc on peut se garder cette idée pour plus tard (mais quand même ce serait intéressant en vue de la démonstration du 8 juin). Je tente une PR si le principe vous va.

**Comment by py-b** [comment]
Idée alternative à l'utilisation de `doremifasol` : ajouter dans `doremifasolData` quelques données formats csv, xls...

**Comment by oliviermeslin** [comment]
Merci @py-b : C'est une bonne idée. Je pense qu'une autre approche pourrait être d'utiliser ce [script](https://github.com/InseeFrLab/utilitR/blob/master/resources/fichiers_plats/scrit_init_fichiers_plats.R), qui importe directement sur le SSP Cloud deux fichiers (un csv et un xlsx).

Ca me fait penser qu'il serait peut-être utile qu'il y ait deux personnes sur l'atelier importation de fichiers plats pour la première matinée, car c'est le plus délicat. A voir avec @GaelleGenin comment elle voit les choses, on pourra en parler demain en réunion.

**Comment by linogaliana** [comment]
@py-b on va pouvoir capitaliser sur l'atelier des matinées de lancement pour revoir certains exemples

**Comment by linogaliana** [comment]
je ferme pour ne conserver que #425
