### ISSUE TITLE
Ajouter une fiche-procédure sur comment bien commencer un projet

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/utilitR#355]
Je me dis qu'on pourrait ajouter à la documentation une fiche de procédure qui donne la marche à suivre sur "comment je crée et configure mon projet en 5 minutes pour m'éviter beaucoup de difficultés plus tard". Je crois que cette idée rejoint une idée que @acazaubiel a proposée il y a quelques mois.

Cette fiche pourrait aborder les points suivants:

- Créer un projet RStudio ;
- configurer le `.gitignore`, le `.Rprofile`, le `.Renviron`... ;
- Mettre en place de quoi gérer les dépendances ;
- etc...

Qu'en pensez-vous?

**Comment by RLesur** [comment]
Je n'en pense que du bien !

Quelques idées de références : https://rstats.wtf/, https://usethis.r-lib.org/, https://rstudio.github.io/renv/index.html et https://books.ropensci.org/targets/

**Comment by acazaubiel** [comment]
Dans ma formation ThinkR, le conseil était simple :
* faites un package using devtools +git
* travaillez dans une vignette  .Rmd en faisant des fonctions
* lorsque vous êtes satisfaits de votre fonction, recopiez là dans R, et ajoutez-y la doc + les tests unitaires
*  faites un check 
* continuez à travailler 
*  faites des commits très fréquemment, des pushs de temps en temps (mais pas trop souvent,, sauf si quelqu'un travaille sur le même fichier que vous en même temps), et chaque push doit être suivi d'un pull
*  rajoutez du code coverage.

Je trouve que la difficulté réside dans les détails : 
* comment est-ce que je gère l'appel aux inputs: 
    * "externes", par exemple stockées sous AUS : je mets le chemin en dur ? (W:/...) ?
    * "internes", par exemple, utiles uniquement sur mon projet, (je les mets dans mon /data   ?)
* comment je gère mes bases intermédiaires ? Pendant la phase de développement, c'est assez utile de les garder, mais elles doivent disparaitre pour l'archivage. D'ailleurs, idem pour la base finale.

**Comment by linogaliana** [comment]
cette question est reliée à #44

**Comment by linogaliana** [comment]
également à #258

**Comment by RLesur** [comment]
Les "détails" que mentionnent @acazaubiel 

> Je trouve que la difficulté réside dans les détails :
> 
> comment est-ce que je gère l'appel aux inputs:
> "externes", par exemple stockées sous AUS : je mets le chemin en dur ? (W:/...) ?
> "internes", par exemple, utiles uniquement sur mon projet, (je les mets dans mon /data ?)
> comment je gère mes bases intermédiaires ? Pendant la phase de développement, c'est assez utile de les garder, mais elles > doivent disparaitre pour l'archivage. D'ailleurs, idem pour la base finale. 

me font réaliser qu'il faut bien faire attention entre un package et un projet d'étude ou d'analyse.

Il y a l'approche de `{targets}` qui commence par la logique "projet d'étude" : 
- un projet avec un dossier `R` dans lequel on met les scripts R
- un dossier `data`
- tous les scripts sont écrits sous forme de fonctions et commentés avec `{roxygen2}`
- on a le script `_targets.R` qui ordonnance les traitements, etc.

Avec, ça on a les bases intermédiaires sauvegardées localement et les traitements ne sont pas relancés si les données d'origine ne changent pas

A un moment de l'étude, on peut vouloir faire un package compagnon qui comprendront les fonctions créées pour l'étude. Dans ce cas, on sort ces fonctions du projet pour les mettre dans un package.

Un exemple est le projet https://github.com/InseeFrLab/lockdown-maps-R, voir par exemple ce commit : https://github.com/InseeFrLab/lockdown-maps-R/commit/4835083e9e74e24f80b8b96e2b86b477a99aa0fd

**Comment by py-b** [comment]
Ça fait beaucoup de choses à penser pour un utilisateur peu familier de tous ces outils.

On pourrait présenter cela par couches successives : 

- incontournables
  - créer un projet RStudio
  - ajouter git
- selon le projet
  - ajouter renv
  - ajouter targets
  - packager ce qui peut l'être
  - ...

**Comment by acazaubiel** [comment]
Je viens de lire la documentation de `{targets}`. C'est **ça** que je veux apprendre. C'est exactement **ça**. Je veux une fiche dessus. C'est exactement ce que tous les chargés d'étude devraient faire lorsqu'ils ont un projet de publication à faire. On a un workflow clair, mis à jour exactement comme il faut, facile à archiver et à reproduire. 
Non, je veux vraiment avoir une fiche et une formation obligatoire pour tous les chargés d'étude dessus. Oubliez toute la merde que j'ai écrite avant.

**Comment by milena-git** [comment]
On pourrait conseiller target pour certains projets d'étude? En présentant d'abord l'utilité pour ce use case ? 

- Projet d'étude en R qui vise à une forte reproductibilité
(e.g. 0 Charger les données, 1. Traiter les données, 2. Produire des résultats, 3. Représenter les résultats)
Pourquoi utiliser target?

* viser la reproductibilité de l'ensemble des étapes de traitement, en tout en minimisant au strict nécessaire la répétition de ces étapes, parfois longues
* adapter des bonnes pratiques de développement en R par l'usage (modulariser son code, assurer la lisibilité des étapes successives du traitement..)

Target permets de définir une chaîne de traitement avec:
* sauvegarde automatique des résultats intermédiaires, des "targets"
* traçabilité de ces résultats intermédiaires par `targets`: lors de la répétition de la chaîne de traitement, ils ne sont mobilisés que si ils sont reproductibles. 
* si une fonction ou un input nécessaire au calcul d'une `target` est modifié, `targets` repère automatiquement les étapes à reconduire, et seulement celles-ci

Ainsi, le lancement du traitement et la vérification de la reproductibilité sont effectués ensemble, au cours du développement du projet, et vérifier la reproductibilité ne revient pas à  'tout relancer' de 0 (ce qui représente un coût élevé). `targets` automatise le travail d'aller-retour dans les étapes d'une étude (j'ai modifié l'étape 1, il faut donc que je relance l'étape 2 qui en dépend...), qui est en pratique rarement mené de façon linéaire, avec des étapes multiples dont on peut perdre de vue les intrications.

**Comment by RLesur** [comment]
La keynote de Maëlle lors des Rencontres R portait exactement sur ce sujet. En plus de targets, elle a également présenté le package orderly https://www.vaccineimpact.org/orderly/index.html

**Comment by linogaliana** [comment]
je ferme cette _issue_ qui n'est plus d'actualité:

- on a une fiche `targets`
- on a des éléments sur ça dans la formation bonnes pratiques qui va + ou - être intégrée dans `utilitR`
