### ISSUE TITLE
A4 de la fiche tidyverse

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#356]
La mise en forme de la fiche tidyverse semble problématique. 

https://www.book.utilitr.org/tidyverse.html

Donne un PDF de +100 pages

**Comment by gilles13** [comment]
il doit y avoir la liste des dépendances du *package*

ok, je sors ...

**Comment by ddotta** [comment]
Pour info, la page sur le tidyverse s'est imprimée correctement ce matin (32 pages), peut-être que vous avez résolu le problème sans le savoir 😄
