### ISSUE TITLE
captures d'écran SSP Cloud

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/utilitR#364]
L'apparence et les fonctionnalités de https://datalab.sspcloud.fr évoluent de manière significative ces derniers temps.

Mettre à jour les captures d'écran de la fiche dédiée lorsque ce sera stabilisé.

**Comment by linogaliana** [comment]
Changement de l'icone "Mes services" ce weekend, à ne pas oublier d'intégrer

**Comment by oliviermeslin** [comment]
@linogaliana , @py-b : vous confirmez que c'est à jour (avec 73ed312c et 3aadba7ccf) ? Si oui, vous pouvez fermer l'_issue_.

**Comment by oliviermeslin** [comment]
Bon, en fait j'ai fait beaucoup de commits. A vous de me dire si ça va.

**Comment by linogaliana** [comment]
sur quelle PR ?

**Comment by oliviermeslin** [comment]
Sur `master` 😊
