### ISSUE TITLE
Hyperlien html cassé 'Partie ggplot2 '

### ISSUE THREAD

**Issue by MurielleL** [InseeFrLab/utilitR#367]
Bonjour,

Le lien donné dans la partie **26.6 Pour en savoir plus** :
- Partie ggplot2 de la formation à R du Ministère de la Transition écologique et solidaire.
n'est plus valide.
 
Le remplacer par: 
https://mtes-mct.github.io/parcours_r_module_datavisualisation/package-ggplot2.html

**Comment by linogaliana** [comment]
merci @MurielleL, [corrigé](39a8a4c74ea3a78e41bc3dc94e9aa39d7a7e5d22)
