### ISSUE TITLE
Un utilitaire pour les zonages à façon

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#368]
Olivier, Lino, si je peux quand même faire une suggestion à celui/celle qui reprendra la fiche, on trouve sur le site de l'Insee un programme R sur les données carroyées à 200 m, utilisé pour sortir des données sur n'importe quel zonage. C'est très pratique et cela pourrait servir aux exemples de jointures dans cette [fiche.](https://www.insee.fr/fr/statistiques/4176290?sommaire=4176305)

_Originally posted by @ThibautLouza in https://github.com/InseeFrLab/utilitR/issues/365#issuecomment-863298524_

**Comment by linogaliana** [comment]
Merci @ThibautLouza, je crée une *issue* spécifique à ta remarque pour ne pas qu'elle soit oubliée lorsqu'on validera #365

**Comment by oliviermeslin** [comment]
Merci @ThibautLouza : tu peux faire toutes les suggestions que tu veux, elles sont très bienvenues!

Une suggestion de ma part: tu devrais te connecter au moins une fois par jour au salon `utilitR-contributeurs`, car ya beaucoup d'infos qui y circulent.

**Comment by ThibautLouza** [comment]
Merci oliviermeslin ☺, c'est vrai que je ne consulte pas régulièrement le salon. C'est un bon conseil que je vais suivre.
Bonne soirée.

**Comment by ThibautLouza** [comment]
Bonjour Lino. Tu as décidé de créer une nouvelle issue mais je pense que ce message aurait eu toute sa place dans l'issue 366 que j'ai précédemment créée. Car il s'agissait simplement pour moi de donner une exemple de jointure spatiale à celui ou celle qui reprendra la fiche, au cas où il/elle serait en panne d'inspiration. Toutefois, ce choix doit être soumis à discussion, car l'exemple n'est pas si simple et nécessite de charger des données carroyées que l'on ne trouve pas forcément dans les packages.

**Comment by linogaliana** [comment]
@ThibautLouza ok merci de la précision. J'ai déplacé le commentaire dans une nouvelle *issue* car je ne savais pas faire dans une *issue* existante. On garde le lien entre les deux en tête (grâce à la citation, `Github` les as automatiquement liées) et on verra pour les fermer conjointement.

**Comment by linogaliana** [comment]
J'ai regardé le code en question. Il fait appel à trop de concepts longs à expliciter pour l'intégrer dans la documentation de manière brute. 

En revanche, j'imagine bien dans une boîte conseil un lien vers celui-ci avec une explication rapide de comment et quand l'utiliser (bref, la nature du problème en question et la solution disponible). @ThibautLouza est-ce que tu te sens de rédiger ce petit paragraphe ? (pas besoin de trop s'étendre)

Il s'agirait de compléter le morceau de code suivant

```r
::: conseil
Blablabla
:::
```

**Comment by ThibautLouza** [comment]
Merci @linogaliana de pourvoir à mon initiation ☺. C'est avec plaisir que je prendrai en charge ce petit paragraphe. Ce sera fait la semaine prochaine.
Je suis assez d'accord avec toi sur le fait que les concepts soient difficiles. D'ailleurs, je t'avoue que j'ai utiliser ce code pour tester mes acquis en R après la lectures des fiches. Même si j'ai compris l'essentiel, certaines choses, comme la fonction "sprintf" par exemple, reste obscure. Mais la question des exemples à trouver reste entière et j'espère que des contributeurs plus expérimentés vont nous trouver des exemples de jointures spatiales.

**Comment by oliviermeslin** [comment]
Salut @ThibautLouza, as-tu pu préparer une proposition de paragraphe (pas d'obligation bien sûr)?

**Comment by linogaliana** [comment]
close by #372
