### ISSUE TITLE
Insérer la palette des couleurs de l'Insee

### ISSUE THREAD

**Issue by ThibautLouza** [InseeFrLab/utilitR#371]
Bonjour, 

je regrette qu'il ne soit expliquer nulle part dans la fiche de ggplot2 la manière d'intégrer dans les graphiques les palettes de couleurs spécifiques à l'Insee.

**Comment by oliviermeslin** [comment]
@ThibautLouza : ce point est très juste. Il me semble que ta question renvoie plus généralement à la question de l'harmonisation de l'apparence des graphiques produits par les agents de l'Insee. A ma connaissance, il n'existe pas de thème `ggplot2` spécifique à l'Insee. Sais-tu s'il en existe un?

**Comment by linogaliana** [comment]
closed by #372

**Comment by linogaliana** [comment]
fausse manip

**Comment by linogaliana** [comment]
Le problème est qu'il n'existe pas de package `R` proposant la palette insee. J'avais crée une palette `ggplot2` Insee sur le modèle de l'ancienne charte graphique (il y a un an). Je n'ai pas regardé si les couleurs ont changé avec la nouvelle charte graphique de l'Insee. 

Le package est privé sur Gitlab. L'ouverture de ce package est un peu *touchy* car peut amener à des débats sur l'utilisation par des tiers de graphiques identifiables comme étant ceux de l'Insee et donc à des débats avec le département de la diffusion dont il s'agit, en principe, d'une prérogative. @RLesur qu'en penses-tu ?

**Comment by RLesur** [comment]
Je pense que dans un premier temps on pourrait rapatrier publinsee en interne. Il faudrait l'adosser à un groupe pertinent sur le gitlab interne.

**Comment by linogaliana** [comment]
Je ferme cette _issue_ qui n'a pas évolué depuis 3 ans
