### ISSUE TITLE
Affiches et flyers

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/utilitR#374]
Afin de balayer plus large que le public des matinées de découverte, j'avais proposé de créer :

- une affiche à placer dans les endroits dédiés des établissements
- un petit flyer qui viendrait en complément et dont le but serait principalement d'avoir l'url du site pour y revenir plus tard

Je n'ai pas de compétences particulières pour la conception de tels documents, mais je veux bien participer.

**Comment by linogaliana** [comment]
Merci @py-b c'est une bonne proposition

**Comment by py-b** [comment]
Non pas d'exemple. Il faudrait a minima le logo, l'objectif de la documentation et une url courte / un QR code. Ensuite on peut broder un peu, mais sans noyer le lecteur sous trop d'information. L'idée étant qu'il se rende sur le site.

**Comment by py-b** [comment]
_pour avis_

J'ai fait une esquisse rapide avec les différents éléments qu'on pourrait inclure (ne pas se focaliser sur les formulations). Naturellement, il faudra reprendre la charte graphique d'utilitR.

![maquette_affiche](https://user-images.githubusercontent.com/8382354/134778878-418b4df9-b818-420a-846a-db401fa965b2.png)

**Comment by oliviermeslin** [comment]
Waouh, ça a l'air trop bien! Merci @py-b! Tu as fait ça comment?

**Comment by py-b** [comment]
Microsoft Paint...

**Comment by jdlom** [comment]
Vous voulez garder le format paysage ou on peut passer en portrait ?

**Comment by py-b** [comment]
@jdlom : laisse libre cours à ta créativité !

**Comment by jdlom** [comment]
Premier jet :
Loin d'être parfait, à vos claviers
![affiche_utilir](https://user-images.githubusercontent.com/8641271/144757576-21f5b54b-0a46-4983-98f0-0dd6c949a4ba.png)

**Comment by jdlom** [comment]
Je vous transmettrai l'ensemble des fichiers si vous souhaitez faire des modifications... 
C'est du gimp, inkscape, que du libre quoi

**Comment by jdlom** [comment]
Mettre le titre UtilitR en utilitR

**Comment by RLesur** [comment]
@jdlom superbe !

**Comment by py-b** [comment]
> * Transformer le titre UtilitR en utilitR
> 
>     * Voir pour les polices à utiliser
> 
>     * Retravailler la partie avec les recommandations (ajouter une ombre ?, changer l'espacement)
> 
>     * Logo tchap (le passer en gris plutôt qu'en couleur ou mettre les autres logo en couleur...)
> 
>     * Mieux centrer [www.utilitr.org](http://www.utilitr.org) avec le logo si l'emplacement du site convient

* Le blanc d'"Objectifs du projet" manque de contraste avec le fond gris clair.

**Comment by jdlom** [comment]
> > * Transformer le titre UtilitR en utilitR
> >   
> >   * Voir pour les polices à utiliser
> >   * Retravailler la partie avec les recommandations (ajouter une ombre ?, changer l'espacement)
> >   * Logo tchap (le passer en gris plutôt qu'en couleur ou mettre les autres logo en couleur...)
> >   * Mieux centrer [www.utilitr.org](http://www.utilitr.org) avec le logo si l'emplacement du site convient
> 
> * Le blanc d'"Objectifs du projet" manque de contraste avec le fond gris clair.
> * ajouter le logo de R quelque part (si on a le droit)

Pour le logo, je pense que ça pose problème au vu de ce post https://opensource.stackexchange.com/questions/2080/can-i-use-the-logo-of-the-r-statistical-package-on-my-webpage
Pour le contraste je suis assez d'accord. Du coups tu suggères que mette un gris plus sombre ?

**Comment by jdlom** [comment]
### v2

- [x] Transformer le titre UtilitR en utilitR

- [ ] Voir pour les polices à utiliser

- [x] Retravailler la partie avec les recommandations (ajouter une ombre ?, changer l'espacement)

- [x] logo tchap (le passer en gris plutôt qu'en couleur ou mettre les autres logo en couleur...)

- [x] Mieux centrer www.utilitr.org avec le logo si l'emplacement du site convient. J'ai espacé les lettre aussi

- [x] Le blanc d'"Objectifs du projet" manque de contraste avec le fond gris clair. Est-ce que c'est suffisant ou tu veux plus ?
- [x]  ajouter le logo de R quelque part (si on a le droit). (voir si l'emplacement convient ou si je je garde l'idée de départ et je le place autre part. En bas à droite à côté du QR code ?



![affiche_utilir_V02](https://user-images.githubusercontent.com/8641271/145688014-f2f1d2ad-551f-4732-8d9e-f920aca022c9.png)

**Comment by jdlom** [comment]
Faut-il que je mette les mentions légales
Ne pas jeter sur la voie publique,
copyright insee
prestataire de la reprographie...

**Comment by py-b** [comment]
> Faut-il que je mette les mentions légales Ne pas jeter sur la voie publique, copyright insee prestataire de la reprographie...

Pas besoin d'être professionnel à ce point, je pense.

**Comment by py-b** [comment]
J'enlèverais le "nous" dans "_Pour nous faire une suggestion_". Ça donne l'impression que les contributeurs forment un cercle fermé. On pourrait aussi trouver une autre formulation pour dire explicitement que n'importe qui peut contribuer.

**Comment by jdlom** [comment]
Je vous propose de réfléchir aux formulations et de revenir vers moi quand
c'est fait pour que j'y apporte les modifications ? Ça te va ?

**Comment by jdlom** [comment]
> > Faut-il que je mette les mentions légales Ne pas jeter sur la voie publique, copyright insee prestataire de la reprographie...
> 
> Pas besoin d'être professionnel à ce point, je pense.

T'es sûr ? Certaines mentions sont normalement obligatoires et d'autres quasiment. On peut faire un truc discret sur le côté. Après c'est vous qui voyez.

**Comment by py-b** [comment]
À voir l'usage qu'on fait de ces affiches. Mon idée initiale était que ça ne sortirait pas à l'extérieur (on ne va pas distribuer dans les boîtes aux lettres par exemple.). Donc pas besoin de faire autant que pour un tract pour un livreur de pizza ?

**Comment by py-b** [comment]
Propostion :
- Titre : _Chacun peut contribuer (aucun prérequis nécessaire)_
- Texte : _Pour signaler ou corriger une coquille, suggérer une amélioration, proposer une nouvelle fiche... :_

**Comment by jdlom** [comment]
![affiche_utilir_V04](https://user-images.githubusercontent.com/8641271/151434746-81e4c837-75ba-4c2e-b20d-a8c3d8cdbbed.png)

**Comment by jdlom** [comment]
Le projet dégueux pas très bien organisé... La prochaine fois je versionnerai cela par git. 
[utilitr-flyer.zip](https://github.com/InseeFrLab/utilitR/files/7953463/utilitr-flyer.zip)

**Comment by py-b** [comment]
C'est parfait ! Merci @jdlom. :1st_place_medal: :star_struck:
