### ISSUE TITLE
référence à un package avec `::`

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/utilitR#375]
(pour ne pas oublier)

Comme souligné par @RLesur, la fiche sur l'installation et utilisation de packages n'évoque que le passage par `library` pour utiliser une fonction d'un package.

Il faudrait toucher un mot de `::`, même si cette syntaxe n'est pas utilisée dans la doc (elle est même déconseillée pour l'écriture d'une fiche utilitR).

**Comment by acazaubiel** [comment]
https://www.pratiques.utilitr.org/comment-renforcer-la-r%C3%A9plicabilit%C3%A9.html ??

**Comment by linogaliana** [comment]
Toujours d'actualité ? Preneur d'une PR sur le sujet si y a une amélioration à faire d'une des fiches

**Comment by tomseimandi** [comment]
@linogaliana ce petit ajout ça le ferait ?
