### ISSUE TITLE
Ajouter une image du bouton "Free unused memory" de RStudio

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#383]
Avec la v1.4 de RStudio, un nouveau bouton a fait son apparition. Il permet de libérer de la mémoire. Il faudrait mettre ça dans la fiche de gestion de la mémoire

**Comment by oliviermeslin** [comment]
@linogaliana : réglé par [ae9522c](https://github.com/InseeFrLab/utilitR/commit/ae9522c41406c437340e3fd96518e66257df6f56)
