### ISSUE TITLE
Brainstorming sur les bonnes pratiques

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/utilitR#388]
Bonjour à tous,

j'ouvre cette _issue_ pour recueillir toutes vos idées autour des bonnes pratiques, dans la perspective de rédiger ensemble un guide de bonnes pratiques pour les selfeurs. Toutes les idées sont les bienvenues. J'anticipe qu'@RLesur va nous parler de ROpenSci, et qu'@acazaubiel va nous parler de `targets`...

**Comment by linogaliana** [comment]
Regarder aussi la `PEP 8` `Python` dans l'optique de normalisation des langages cousin

**Comment by RLesur** [comment]
Voici les idées que je soumets au débat.

Le principe général que j'ai à l'esprit est de ne pas réécrire depuis 0 un guide de bonnes pratiques mais s'appuyer sur un ou plusieurs guides faisant "autorité" dans la communauté R. Contrairement à python qui a PEP 8, R n'a pas l'équivalent, ce qui est très gênant.  
_Par exemple, j'aime beaucoup la présentation du [Google's style guide](https://google.github.io/styleguide/Rguide.html) qui est présenté comme un fork du [Tydiverse Style Guide](https://style.tidyverse.org/) en modifiant/adaptant quelques points. _

**Que choisir comme guides de référence ?**

Ma référence pour le développement de packages est effectivement **rOpenSci** https://devguide.ropensci.org/

Pour le style de code, il est difficile de dire que le Tidyverse Style Guide n'est pas la référence en la matière.

Pour les pipelines analytiques, c'est le plus compliqué je trouve car il y a évidemment targets mais pas seulement.

**Comment by CTassart** [comment]
Bonjour,

Beaucoup d'agent·e·s commence à coder (en R notamment) parce que leur poste le nécessite : il·elle·s suivent les 1ères formations "institutionnelles", puis se débrouille au quotidien, sans maîtriser, connaître et/ou appliquer les règles de bonnes pratiques qui, par ailleurs, ne sont pas forcément claires ni mêmes définies pour la programmation avec R.

il me semble important que les bonnes pratiques soient également intégrées, rapidement, dans le cursus des formations INSEE.
Peut-être serait-il intéressant de se rapprocher des personnes "compétentes" en la matière ?

**Comment by py-b** [comment]
Pour mémoire, une _issue_ connexe : https://github.com/InseeFrLab/utilitR/issues/355 (attention, contient une envolé lyrique de @acazaubiel)

**Comment by avouacr** [comment]
Tout à fait d'accord avec @linogaliana. Il me semble que le sujet des bonnes pratiques peut (et gagnerait à) être traité de manière agnostique au langage utilisé. Cela permettrait de souligner les idées fondamentales derrière ces pratiques (le code comme outil de communication, pour soi futur et pour les autres, réflexion en projet voire package, nécessité du contrôle de version, réflexion sur l'environnement d’exécution de l'application..) indépendamment de leur implémentation. Et bien sûr cela éviterait d'avoir à éditer des guides similaires pour les différents langages utilisés en statistique publique, voire qui pourraient émerger dans le futur.

Je trouve aussi pertinent de présenter les bonnes pratiques comme un continuum de reproductibilité, sur lequel on se placerait en fonction de ses aspirations (portée du projet, potentiel collaboratif, potentiel évolutif, etc.) et de ses contraintes (ressources humaines, temps, etc.). Dans la progression que tu suggères @linogaliana -- et à laquelle je souscris complètement -- il me semble clair que les principes sous-jacents à chaque étape sont assez indépendants du langage utilisé. Dans 1, 2 et 5 il est possible d'expliquer les principes communs, tout en renvoyant aux guides de référence propres à chaque langage, qui ont été suggérés dans la conversation.

**Comment by avouacr** [comment]
Hello,

Dans l'optique d'interventions à l'Ensae sur le sujet au cours de l'année, j'ai rédigé un [plan détaillé](https://github.com/avouacr/bonnes_pratiques) de ce que j'imaginerais être un guide de bonnes pratiques pour projets de données. Vu que cela recoupe largement ce dont on a discuté dans le cadre de ce thread et de la réunion de vendredi, je le soumets à la discussion communautaire ici, peut être que cela peut servir de base aux suites du brainstorming ?

Le syllabus est construit selon les principes que je proposais dans la discussion :
- non centré autour d'un langage particulier, en faisant référence aux standards de chaque langage lorsque cela est pertinent ;
- autour d'une idée d'un continuum de bonnes pratiques, sur lesquelles on se placerait en fonction des ambitions/ressources/contraintes de son projet. Et donc une structure basée sur une progression, aussi bien au fil des sections qu'au sein des sections.

Je suis preneur de tout retour :)

**Comment by acazaubiel** [comment]
Je comprends la philosophie générale, c'est juste que les agents de L'Insee commencent à peine à être opérationnel sous R. Leur présenter un nouveau document dans lequel on présente Python comme l'avenir passera assez mal pour plein de raisons :
- de nombreuses chaînes de production sont encore en SAS, donc on a même pas fini de transiter vers R ;
- le coût fixe de la transition sas vers R n'a pas encore été amorti par des gains d'efficacité ;
- la transition à été (globalement) assez laborieuse, avec beaucoup d'auto-formations et de bricolage ;
- la position officielle de l'institut n'est pas de basculer vers Python, à ma connaissance, donc la légitimité à en faire est plus faible.
-
Bref, je pense que ce serait une mauvaise idée de mettre les deux langages sur le même plan. R est privilégié politiquement à l'Insee, c'est donc celui qu'il faut mettre en avant, surtout si on cherche à parler à tous les agents.

**Comment by avouacr** [comment]
@acazaubiel 

Je pense que personne ici ne suggère de présenter Python comme l'avenir de l'Insee. En tout cas, à titre personnel, ce n'était pas du tout mon intention et je ne trouverais d'ailleurs pas pertinent de donner cette orientation à un éventuel guide des bonnes pratiques à usage SSP. L'enjeu est plutôt, comme cela a été souligné par @jeremylhour et @linogaliana, de tenir compte, sans pour autant se positionner, de plusieurs constats : 

- le cocktail des langages enseignés dans les écoles de statistique évolue rapidement, et tend à se biaiser au profit de Python, reflétant un mouvement général de transition vers des formations en data science, souvent centrée sur Python ;
- par conséquent, et aussi dans la perspective des recommandations du rapport DINUM-Insee sur la valorisation des compétences data, il est probable que Python prenne de fait de l'importance dans le SSP dans les années à venir, dans la mesure où il constitue un langage commun à l'ensemble des professions "data" qui sont amenées à se développer, et est également mieux adapté que R à la production ;
- R et Python sont de fait des langages proches, qui partagent la même philosophie, très éloignée de celle de SAS par exemple. Du coup, les bonnes pratiques qui s'appliquent à l'un s'appliquent quasi de manière automatique à l'autre -- modulo quelques subtilités d'implémentation. Je pense qu'il est aussi essentiel de noter que le fait de transitionner de SAS vers des langages comme R et Python n'est pas qu'un choix technique, mais traduit la place croissante prise par le développement et les outils libres dans le métier de statisticien. A ce titre, il me semble qu'un guide des bonnes pratiques doit souligner le changement de culture qui doit s'opérer, en s'inspirant des bonnes pratiques en vigueur dans la communauté des développeurs, qui sont pour la plupart indépendantes du langage de programmation.

Je reste cependant tout à fait d'accord avec toi sur le fait qu'il faut absolument éviter l'écueil de produire un guide trop théorique. Dans tous les cas, le guide pratique de référence pour devenir "opérationnel sous R" resterait clairement utilitR. Il me semble qu'il est un peu vain de vouloir évoquer le sujet des bonnes pratiques trop tôt dans la formation des agents, dans la mesure où il faut avoir suffisamment de pratique du langage pour bien saisir en quoi il est important d'améliorer ses pratiques. Du coup, faire un guide relativement agnostique au langage (tout en mettant R au premier plan des implémentations) ne me semble pas incompatible avec la problématique de former correctement à R des personnes qui n'en ont jamais ou peu fait.

Sinon, +1 pour la présentation onglets en mode doc Spark, et +1 pour les templates de début de projet.

**Comment by acazaubiel** [comment]
Hehe, ce thread est hyper intéressant (même si je passe pour le vieux relou)! :) 

En définitive (et comme souvent par écrit), nos différences sont je pense plus minimes que ce qui nous rassemble.
Je veux simplement alerter un point qui me semble important dans la manière de présenter les choses pour les agents de l'Insee. 

Si on s'y prend mal, ce guide peut être lu/vu comme une recommandation "en creux" à faire du Python comme on pourrait faire du R. Je pense que cette recommandation ne passera pas auprès des agents de l'Insee, pour toutes les raisons évoquées si dessus. 

Je comprends néanmoins tes remarques sur la domination croissante de Python vis-à-vis de R, et c'est un vrai enjeu pour l'institut...

Si vraiment on veut garder du Python dans ce guide, je pense qu'il faut l'amener à travers l'idée que ce guide ne s'applique pas uniquement à l'Insee mais aussi dans le reste du SSP, et au-delà dans la sphère privée.

**Comment by linogaliana** [comment]
Merci @jeremylhour pour `kedro` ça a l'air exactement ce que je cherchais comme librairie pour un de mes projets.

Ca pourrait être le contrepoint `Python` de `targets` (`R`) si ça marche bien (à tester)

**Comment by MaelTheuliere** [comment]
Hello, très intéressant ces échanges. Histoire d'alimenter la biblio, je vous transmets le lien vers les guides qui compilent les bonnes pratiques identifiées dans le cadre de la démarche propre : 
- la théorie : https://rdes_dreal.gitlab.io/propre/index.html
- la pratique : https://rdes_dreal.gitlab.io/publication_guide/

**Comment by ddotta** [comment]
Hello, discussion très intéressante merci beaucoup !  
J'ai simplement une remarque technique à faire sur la proposition d'onglets que je trouverais très pratique en effet pour basculer entre les langages.  

> Quant à la présentation, j'imagine bien un système d'onglet permettant de facilement basculer d'un langage à l'autre. La [doc de spark](https://spark.apache.org/docs/latest/sql-getting-started.html) donne un bon exemple de ce que ça donne

J'avais fait quelques tests sur un autre projet et je m'étais rendu compte que la technique des `{.tabset}` expliquée [ici](https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html) ne fonctionnait pas avec un `bs4_book` comme utilisé [dans utilitr](https://github.com/InseeFrLab/utilitr-template/blob/e30a8e1ca4ca57b8f5308ca4cac01ece37ec5055/R/build_website.R#L95:L125)

Et autre question : même en cas de contournement très probable de ce problème par les brillants mainteneurs de ce dépôt 🤣 je me pose la question de l'articulation de ces onglets avec [utilitr::html_paged](https://github.com/InseeFrLab/utilitr-template/blob/e30a8e1ca4ca57b8f5308ca4cac01ece37ec5055/R/pdf_document.R#L15) issue de {pagedown}.  
Comment cela pourra être gérer lorsqu'un lecteur voudra imprimer la fiche sur les bonnes pratiques ? (s'il veut que l'impression pdf contienne le code R ou python)

**Comment by linogaliana** [comment]
Salut @ddotta ce sont de bonnes questions !

Pour les onglets sur le site web, je m'inquiète pas trop je pense qu'on peut trouver une implémentation, peut-être à base de _fenced divs_ pandoc. Je l'ai fait en `blogdown` pour mon cours python ([ici](https://linogaliana-teaching.netlify.app/reads3/)) en m'insipirant du shortcode `hugo` du thème Hugo Apero (exemple pour le cours de 3A qu'on fait avec @avouacr [ici](https://hungry-hodgkin-0a5a81.netlify.app/code-architecture/)).

En ce qui concerne le `print` il y a une petite stratégie à adopter. J'ai l'intuition que pour le print, transformer le panelset en encadré avec des parties correspondant aux onglets serait pas mal (je me dis que pour le print, pour le coup, on met les deux langages). On pourra ouvrir une _issue_ spécifiquement sur cette technique quand on tentera ce système d'onglets

**Comment by linogaliana** [comment]
@jeremylhour  j'ai un peu étudié la question des _pipelines_ côté `python`. `kedro` n'est toujours pas passé à une version récente de `python` donc ça me paraît compliqué de le recommander en alternative de `targets`.

En revanche, j'ai commencé à pas mal utiliser `snakemake`, c'est vraiment pas mal. Cela fait écho à une discussion qu'on avait eu sur `grrr` avec @juba. `snakemake` est moins intuitif à la prise en main que `targets` mais ça fonctionne bien (je vais essayer à terme d'ajouter un tuto `snakemake` dans mon cours python).

**Comment by ddotta** [comment]
[Un article de blog ](https://blog.r-hub.io/2022/03/21/code-style/) écrit cette semaine sur le sujet qui contient des liens intéressants sur le sujet de cette issue (dont certains ont déjà été évoqués)

**Comment by linogaliana** [comment]
je ferme puisque maintenant on a la formation bonnes pratiques + des chaptires utilitr consacrés
