### ISSUE TITLE
Problèmes fiches SAS

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#403]
Retour d'un utilisateur de la doc reçu par mail

- [x] Parties 15.3.1.1 et 15.3.1.2 : les doubles quotes sont en trop dans : %let versR = "D:/le/dossier/pour/exporter/le/fichier/csv" ;
Elles font en effet doublon avec celles que l’on retrouve dans : filename f "&versR./data.csv" encoding = "utf8" ;
- [x] Partie 15.3.1.2 : il manque un s à proc contents dans : PROC CONTENT DATA = ma_table_SAS OUT = labelVar ;
- [x] L’étape data ci-dessous n’a pas de raison d’être car les noms des variables en sortie de la proc contents sont déjà name et label.
> DATA labelVar (RENAME = (_name_ = name _label_ = label)) ;
> SET labelVar ;
> RUN ;
- [x] J’ai par ailleurs une question concernant la partie 15.3.2. Je ne parviens pas à associer les étiquettes avec les variables avec la commande label(df_sas) <- lapply(labels_sas, function(x) x). Aurais-tu une explication ?

**Comment by py-b** [comment]
Les points 1 et 2 sont exacts.

Pour le point 3, le code cité ne correspond pas à ce qui est écrit dans la fiche : `label(df_sas) <- lapply(labels_sas, function(x) x)`

Pour le point 4, aucune idée. Je ne sais même pas d'où vient la fonction `label<-` (et accessoirement, `identity` est plus élégant que `function(x) x`. :stuck_out_tongue: )

**Comment by py-b** [comment]
Points 1 & 2 corrigés via e7b5e615243dc08e73e34.

**Comment by py-b** [comment]
Pour le point 4, j'ai relu la fiche et vu qu'on parlait du package `{sjlabelled}`.

Je me demandais si on a vraiment besoin de ce package.

En effet, les 2 lignes suivantes donnent le même résultat pour extraire les labels :
```r
sapply(dfRP, attr, "label")
sjlabelled::get_label(dfRP)
```

Quant à l'instruction qui pose problème, je n'ai pas réussi à la faire fonctionner même avec `sjlabelled`.

**Comment by py-b** [comment]
Pour attribuer les labels, je n'ai trouvé qu'une solution de ce type :

```r
# sans sjlabelled
iris[] <-
  Map(
    function(var, lib) {attr(var, "label") <- lib ; var},
    iris,
    letters[1:5]
  )

# avec sjlabelled
iris[] <-
  Map(
    sjlabelled::set_label,
    iris,
    letters[1:5]
  )
```

Les 2 solutions utilisent `Map` et un crochet à gauche de l'affectation pour garder les attributs de data.frame. Quelqu'un voit plus simple ?

**Comment by py-b** [comment]
Après vérification, le renommage du point 3 était aussi inutile. Corrigé via b3be44b7ea0122f8e72f96d5439ab8939f94ffb9.

**Comment by py-b** [comment]
Point 4 résolu par f9f6d64821252f607f6cb4adda7f7f2e6a3d76c9.
