### ISSUE TITLE
Rendu du site sur mobile

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#409]
Le site ne rend pas bien sur mobile, il dépasse largement et la table des matières n'est pas déroulable. Il y a quelques règles CSS à revoir pour ça

**Comment by ddotta** [comment]
@linogaliana mon commentaire date un peu mais dans mon souvenir l'affichage sur mobile était ok avec mes essais.  
Par contre, je n'avais pas mesuré les conséquences ou les pertes engendrées par `extra_dependencies = list()`
A suivre
