### ISSUE TITLE
Mentionner arrow pour lire des données sur S3

### ISSUE THREAD

**Issue by RLesur** [InseeFrLab/utilitR#412]
Actuellement, la partie [Utiliser des données stockées sur le système de stockage S3](https://www.book.utilitr.org/sspcloud.html#utiliser-des-donn%C3%A9es-stock%C3%A9es-sur-le-syst%C3%A8me-de-stockage-s3) s'appuie sur `{aws.s3}`.

Etant donné que `{arrow}` a un support intégré pour S3, je me demandais si ça ne vaudrait pas la peine de le mentionner.  

A la limite, si on ne traitait que de données dans cette partie (`csv`, `parquet`...), `{arrow}` pourrait presque se suffire à lui-même (`{aws.s3}` reste néanmoins utile pour les autres formats de fichier).

Exemple : 

```r
library(arrow)
library(tidyverse)

minio <- S3FileSystem$create(
  access_key = Sys.getenv("AWS_ACCESS_KEY_ID"),
  secret_key = Sys.getenv("AWS_SECRET_ACCESS_KEY"),
  session_token = Sys.getenv("AWS_SESSION_TOKEN"),
  endpoint_override = Sys.getenv("AWS_S3_ENDPOINT")
)

# long : 
minio$ls("donnees-insee", recursive = TRUE)

df <- open_dataset(minio$path("donnees-insee/FILOSOFI/2017/FILOSOFI_DISP_PAUVRE_DEP_OCCTYPD2.csv"), delimiter = ";")

df %>%
  summarise(count = n()) %>%
  collect()
```

**Comment by linogaliana** [comment]
ça me paraît une bonne proposition. En effet, on pourrait éventuellement adapter la recommandation et les exemples pour donner une place à `arrow`. Pour interfacer avec `data.table`, il faut faire un  `setDT`, on est d'accord ? (j'ai le souvenir d'une brouille entre Matt Dowle et l'équipe Arrow, je suppose que ça a pas aidé à renforcer la connexion entre ces packages)

**Comment by RLesur** [comment]
> Pour interfacer avec data.table, il faut faire un setDT, on est d'accord ? (j'ai le souvenir d'une brouille entre Matt Dowle et l'équipe Arrow, je suppose que ça a pas aidé à renforcer la connexion entre ces packages)

Bonne question. Si les données sont en parquet, je ne suis pas sur qu'utiliser data.table soit pertinent. Pour du csv, je pense que le mieux est d'enchainer un `read_delim_arrow()` avec un `setDT`.

**Comment by linogaliana** [comment]
je ferme puisque cette question va être réglée par la prochaine mise à jour de la fiche
