### ISSUE TITLE
Bloc specificite mal inséré

### ISSUE THREAD

**Issue by a-alexandre** [InseeFrLab/utilitR#437]
Bonjour,

J'ai remarqué un bug d'affichage d'un bloc `specificite` à cette page : 
[https://www.book.utilitr.org/gerer-dependances.html#renv](https://www.book.utilitr.org/gerer-dependances.html#renv)

Dans la source cela se situe ici :
[https://github.com/InseeFrLab/utilitR/blob/master/03_Fiches_thematiques/Fiche_gerer_dependances.Rmd#L396-L398](https://github.com/InseeFrLab/utilitR/blob/master/03_Fiches_thematiques/Fiche_gerer_dependances.Rmd#L396-L398)

**Comment by py-b** [comment]
Merci @a-alexandre ! C'est corrigé.
