### ISSUE TITLE
  Init file needs to be updated due to new pod configurations

### ISSUE THREAD

**Issue by fBedecarrats** [InseeFrLab/utilitR#438]
(This is a duplicate from: https://github.com/InseeFrLab/formation-r-lissage-spatial/issues/4) 
I ran into problems with my init.sh files this morning. I open this issue for other SSP Cloud users that might need it. Please do not consider if your pods are running correctly.
New default path/users for RStudio pods require updating init.sh files: 
- Project paths were `/home/rstudio/...`, they are now `/home/onyxia/work/...` (where  ̀...` should be replaced by project name)
- User names were "rstudio:users", they are now "onyxia:users"
- The test for .Rprofile hook was `if (newSession && identical(getwd(), path.expand('~')))`, which doesn't seem to work anymore; replacing with `if (newSession && !identical(getwd(), \"'$WORK_DIR'\"))` works in my case (where `WORK_DIR̀` should be replaced by the variable name given to the project directory in the init.sh file.

**Comment by linogaliana** [comment]
Thanks @fBedecarrats for opening the _issue_ and suggesting some changes. @pierre-lamarche made the required change in #440
