### ISSUE TITLE
Enrichir la fiche BDD avec duckdb

### ISSUE THREAD

**Issue by ddotta** [InseeFrLab/utilitR#447]
Après la présentation faite en interne à l'Insee aujourd'hui sur [duckdb](https://duckdb.org/), il serait peut-être intéressant d'enrichir la fiche sur [comment travailler avec les bases de données](https://www.book.utilitr.org/bdd.html) ?  
Cela pourrait être utile pour les personnes qui utilisent les BDD du point de vue analytique et pas transactionnel...

**Comment by pierre-lamarche** [comment]
Je ne suis pas sûr que c'était dans le champ initial de la fiche sur les bases de données. Par exemple, on ne fait qu'une référence très élusive à `SQLite`, or si on se met à parler de `duckdb`, il faut être complet sur ce sujet. Pour moi la fiche porte sur des bases de données au sens VM du terme, pas aux SGBD "système de fichier". Mis à part le fait de mentionner l'existence du package, je ne vois pas trop ce qu'on peut faire d'autre : le principe de connexion est le même que pour les autres solutions, et il n'y a pas vraiment de choses spécifiques sur la façon dont on manipule les données.
