### ISSUE TITLE
Enrichir la partie consacrée au format parquet

### ISSUE THREAD

**Issue by ddotta** [InseeFrLab/utilitR#448]
Sur le format de données parquet, il en est question [à cet endroit](https://github.com/InseeFrLab/utilitR/blob/master/03_Fiches_thematiques/Fiche_targets.qmd#L329-L334).  
Compte-tenu de l'importance que peut prendre ce type de fichiers dans l'utilisation de données volumineuses avec R, peut-être serait-il envisageable de créer une fiche supplémentaire dans la partie `IMPORTER DES DONNÉES AVEC R` ?  
Il pourrait être par exemple question de :  
- son interopérabilité
- ses performances
- sa logique de partitionnement
- sa compatibilité avec la syntaxe dplyr
- ses limites ...

**Comment by ddotta** [comment]
Une source d'inspiration écrite par @ericemc3  
https://github.com/InseeFrLab/utilitR/pull/451#issuecomment-1396628619

**Comment by linogaliana** [comment]
J'ai une version python dont on peut aussi s'inspirer (faut que je l'enrichisse avec `duckdb`) : https://pythonds.linogaliana.fr/reads3/

**Comment by ddotta** [comment]
👍  Top @linogaliana ta doc sur python est vraiment hyper riche !

**Comment by linogaliana** [comment]
@ddotta Il me semble qu'on a ajouté pas mal d'éléments sur parquet ces derniers temps. si tu penses qu'il y a encore des choses à faire, tu peux réouvrir l'issue
