### ISSUE TITLE
Typos sur la dernière MAJ du site

### ISSUE THREAD

**Issue by acazaubiel** [InseeFrLab/utilitR#467]
Hello,

J'ouvre donc cette issue pour faire part des petites scories qui resteraient : 

- Entre les chapitres 13 et 14, la partie "Manipuler des données avec R" n'apparait pas en gras, mais avec un préfixe (PART)  (bandeau de gauche)

**Comment by py-b** [comment]
Problème également dans le sommaire au chapitre 24

**Comment by linogaliana** [comment]
- @acazaubiel déjà remarqué et corrigé dans #466

**Comment by oliviermeslin** [comment]
Il me semble que le problème est réglé. Je ferme l'_issue_, rouvrez-la si problème est toujours là.
