### ISSUE TITLE
Specificites sans accents

### ISSUE THREAD

**Issue by ddotta** [InseeFrLab/utilitR#470]
Hello,  
Depuis le passage à quarto, les box `Specificités de l'Insee` s'écrivent `Specificites` (sans accent).  
J'ai essayé rapidement de rajouter un accent `é` avec `\u00e9` ou `&eacute;` mais ça n'a pas l'air de bien se passer dans le fichier scss.  
Du coup, une proposition pourrait être soit de :  
1. remplacer "Specificités" par un synonyme sans accent :monocle_face: (pour l'instant j'en ai pas trouvé)
2. remplacer "Specificités" par "Insee"

Je pencherais plutôt pour la solution 2 pour laquelle je vais vous proposer une PR.
Si vous trouvez un hack pour corriger le soucis (ou un meilleur synonyme), ne tenez pas compte de la PR !

**Comment by oliviermeslin** [comment]
On pourrait mettre "Si vous travaillez à l'Insee", ou "Et quand on travaille à l'Insee?"

**Comment by py-b** [comment]
@oliviermeslin : bien tenté mais il reste le problème du "à" dans tes propositions

**Comment by linogaliana** [comment]
je ferme car j'ai abandonné le principe des box custom
