### ISSUE TITLE
Précision sur la fiche "parquet"

### ISSUE THREAD

**Issue by jllipatz** [InseeFrLab/utilitR#478]
Bonjour,

Il est écrit qu'on ne peut pas charger les 100 premières lignes d'un fichier parquet. Dans l'absolu c'est possible de la faire, mais il ne faut pas utiliser `read_parquet()` qui n'a aucune option pour cela; Il suffit de faire un `open_dataset()` puis un `head()`.
Remarque complémentaire : `read_parquet()` ne lit pas vraiment le fichier au sens que ce qui est lu peut encore demander du temps de calcul.

**Comment by acazaubiel** [comment]
Il me semble que le commit b59e70d d'Olivier répond à cette remarque dans  #476
