### ISSUE TITLE
Lien mort

### ISSUE THREAD

**Issue by e-cupi** [InseeFrLab/utilitR#479]
Dans cette rubrique https://www.book.utilitr.org/03_fiches_thematiques/fiche_configurer_git, dans l'encadré "Conseil", le lien dans la phrase "Plus d’éléments sur les jetons d’accès sont disponibles [ici](https://happygitwithr.com/credential-caching.html#get-a-pat)" est mort.
=> on veut renvoyer là ? https://happygitwithr.com/https-pat.html

**Comment by ddotta** [comment]
Bien vu @e-cupi et merci !
