### ISSUE TITLE
Ajouter la licence dans la page de présentation du projet

### ISSUE THREAD

**Issue by RLesur** [InseeFrLab/utilitR#485]
La licence est présente dans le repository mais il n'est pas fait mention de cette licence dans le document.

Sa place la plus naturelle serait dans la page de présentation, après mention des auteurs.

**Comment by linogaliana** [comment]
- @RLesur : proposition dans #493 , c'est ça que tu avais en tête ?

**Comment by RLesur** [comment]
> - @RLesur : proposition dans #493 , c'est ça que tu avais en tête ?

Oui, exactement
