### ISSUE TITLE
Nouvelle fiche : dates et données temporelles

### ISSUE THREAD

**Issue by TanguyBarthelemy** [InseeFrLab/utilitR#491]
Il manque peut être une fiche qui concerne le traitement des **dates** et des **séries temporelles**.

Peut être que certains ont déjà réfléchis à cette question. J'ai déjà une structure en tête que je vous propose ici :

## Afficher des séries temporelles (`plot`, `ggplot2`, `dygraph` ?, `highcharter` ?)

C'est un premier brouillon. Si vous avez d'autres idées, des modifications, je serai ravi d'en discuter et d'adapter le plan de la fiche. 

Pour ma part j'utilise principalement les packages `base`, `stats`, `lubridate` et `zoo` pour le traitements des dates et objets `ts` mais si d'autres sont recommandés et si vous les connaissez bien, on peut les inclure facilement à la feuille.

Merci !

**Comment by RLesur** [comment]
Merci pour la proposition !
Quelques petites suggestions en ce qui me concerne : 

- saisir l'opportunité de cette fiche pour expliquer (sous forme d'encadré ?) les normes ISO 8601 et RFC 3339, je constate au quotidien que ces normes ne sont pas connues et cela m'attriste terriblement
- expliquer l'impact des locales et comment gérer proprement les changements d'heure (quel enfer) : là aussi, cela aurait plutôt sa place dans un encadré

**Comment by acazaubiel** [comment]
Hello, la proposition est super intéressante.

Je ne fais pas beaucoup (et pas assez) de séries temporelles, mais je pense qu'on a l'opportunité de se raccrocher en fin de fiche à JDemetra via le package `RJDemetra`. Concernant tes _packages_, ils me semblent hyper classiques (et indispensables).
