### ISSUE TITLE
Apporter des précisions sur le partitionnement et sur l'autre façon d'optimiser un dataset (trier par une variable)

### ISSUE THREAD

**Issue by nbc** [InseeFrLab/utilitR#522]
Partitionner un dataset sur une variable pouvant être vide ou NA pose des problèmes de compatibilité entre les outils, duckdb et arrow ne se comportant pas de la même façon. Ce comportement est à priori hérité de apache hive cf https://kb.databricks.com/data/null-empty-strings.

Pour éviter les problèmes et conserver une optimisation dans les cas ou une variable peut être NA ou vide, il faut conseiller de trier le fichier parquet par la variable plutôt que de partitionner. Cette optimisation est un peu moins performante (la librairie utilisée doit lire tous les métadonnées des row groups plutôt que les répertoires) mais reste très efficace et est supportées par toutes les librairies.

J'essaye de trouver le temps de faire un PR.

**Comment by nbc** [comment]
```

**Comment by nbc** [comment]
Un exemple inverse : 

```
library(duckdb)
library(arrow)
library(dplyr)

con <- dbConnect(duckdb())

data <- tibble::tibble(col1 = c("1", "", NA), col2 = c("a", "a", "a"))
duckdb_register(con, "data", data)

dbExecute(con, "COPY (FROM data) TO 'duckdb' (FORMAT PARQUET, PARTITION_BY (col1))")
dbGetQuery(con, "FROM read_parquet('duckdb/**/*.parquet')") |> as_tibble()

open_dataset("duckdb", partitioning = schema(col1 = utf8())) |>
  collect()
```

**Comment by nbc** [comment]
Impossible de lire un dataset partitionné sur une variable numérique par arrow avec duckdb : 

```
library(duckdb)
library(arrow)
library(dplyr)

tibble(col1 = c(1, 2, NA), col2 = c("a", "a", "a")) |>
  write_dataset("arrow", partitioning = "col1")

open_dataset("arrow", partitioning = schema(col1 = int16())) |>
  collect()

dbConnect(duckdb()) |>
  dbGetQuery("FROM read_parquet('arrow/**/*.parquet', hive_partitioning = true, hive_types = {'col1': INT})")
```

**Comment by linogaliana** [comment]
introduit avec d5f7809

**Comment by ericemc3** [comment]
Le consensus sur l'opportunité du partitionnement est que chaque élément de la partition fasse un minimum de 500 Mo/1Go, ce qui réduit l'oportunité des cas d'usages me semble-t-il pour la stat publique.
De plus, un fichier partitionné est moins facilement maniable, transférable et accessible en ligne, sauf s'il est sur S3 par exemple.
Mieux vaut, peut être, se concentrer sur les bons critères de tri, le typage des colonnes et la taille des row-groups?
