### ISSUE TITLE
Problème d'affichage block callout

### ISSUE THREAD

**Issue by MaryleneH** [InseeFrLab/utilitR#528]
Sur la [page](https://book.utilitr.org/02_Bonnes_pratiques/02-structure-code.html) , problème d'affichage

::: {.callout-important} ## Tâche concernée et recommandation - Il est recommandé d’utiliser systématiquement les projets RStudio dans des projets impliquant des programmes R. - Il est recommandé de structurer les projets en dossiers thématiques (données, code, sorties, documentation) et d’organiser ces dossiers afin de séparer les entrées d’une chaîne de traitement, les objets intermédiaires et les sorties. - Il est recommandé d’adopter des noms signifiants pour les fichiers et de ne jamais utiliser des espaces dans les noms de dossiers et fichiers. - Il est recommandé d’accorder une attention particulière au fichier README.md. :::

**Comment by oliviermeslin** [comment]
@MaryleneH C'est réglé je crois. Rouvre l'issue si tu penses qu'il y a toujours un problème.

**Comment by MaryleneH** [comment]
Il y a encore le problème d'affichage 😺
