### ISSUE TITLE
Réparer binder

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#59]
In GitLab by @RLesur on May 20, 2020, 09:51

binder est cassé, même cause que #58

**Comment by linogaliana** [comment]
In GitLab by @RLesur on May 21, 2020, 21:02

mentioned in merge request !49

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on May 26, 2020, 12:16

Closed by !49

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on May 26, 2020, 12:16

closed

**Comment by linogaliana** [comment]
In GitLab by @RLesur on Jun 25, 2020, 11:40

Autre erreur maintenant liée à https://github.com/rocker-org/rocker-versioned2/blob/e315343c88379e63f42f2f69772731ca5496b646/scripts/install_binder.sh#L4

Il faut changer la variable d'environnement `PYTHON_VENV_PATH`

**Comment by linogaliana** [comment]
In GitLab by @RLesur on Jun 25, 2020, 11:40

reopened

**Comment by linogaliana** [comment]
In GitLab by @RLesur on Jul 2, 2020, 21:51

mentioned in merge request !61

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Jul 7, 2020, 13:17

mentioned in merge request !62

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Jul 10, 2020, 22:48

@RLesur, @linogaliana: Cette _issue_ est-elle réglée (je ne comprends pas vraiment de quoi il retourne)?

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Jul 11, 2020, 11:38

Il faut faire le *merge* en local, je dois y penser quand j'ai ordi avec git à disposition, pas comme maintenant

**Comment by linogaliana** [comment]
In GitLab by @RLesur on Jul 11, 2020, 16:19

il me semble qu'il suffit de merger !62

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Jul 11, 2020, 16:31

C'est fait. Ca fonctionne?

**Comment by oliviermeslin** [comment]
@linogaliana, @RLesur : cette _issue_ est-elle toujours d'actualité?

**Comment by linogaliana** [comment]
Je pense qu'elle l'est toujours. Je n'ai pas fait le nécessaire pour remettre un service binder en ordre dans gha

**Comment by RLesur** [comment]
J'ai essayé de le réparer la semaine dernière. De gros problèmes de compatibilité entre jupyter et rstudio sont apparus ces derniers mois. Je me suis baladé sur plusieurs projets tel que <https://github.com/Robinlovelace/geocompr>. Leurs binder est aussi cassé. J'ai de gros doutes sur le fait que ce soit réparable facilement.  
Je me demande s'il ne faudrait pas laisser tomber Binder le temps que la communauté trouve une solution.

**Comment by linogaliana** [comment]
Oui je propose de laisser le temps à la communauté de trouver une solution. Quand elle existera, on l'adoptera.
