### ISSUE TITLE
Eviter l'utilisation de l'extension .PNG

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#72]
In GitLab by @linogaliana on Jun 19, 2020, 07:25

`.PNG` fonctionne mal avec l'intégration continue, alors que `.png` ne génère aucun problème. 

Le `.PNG` est généré automatiquement par l'outil capture de Windows. Il faut éviter que les fichiers `.PNG` soient commités car c'est un peu la galère après pour revenir sur du `.png` avec `git`.

@RLesur penses-tu qu'on puisse gérer ça avec un `git hooks`?

**Comment by linogaliana** [comment]
In GitLab by @RLesur on Jun 19, 2020, 11:45

en théorie, je dirais oui, mais ce qui n'est pas simple : 

- si on veut le configurer côté serveur j'ai l'impression qu'il faut être administrateur de l'instance git cf. https://docs.gitlab.com/ee/administration/server_hooks.html
- si on veut le configurer côté client, le partage d'un git hook n'est pas trivial (mais certainement faisable en combinant les différentes réponses à cette question https://stackoverflow.com/questions/427207/)

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Jun 19, 2020, 14:02

Merci, je vais y réfléchir.

C'est une idée en l'air on verra si elle atterit sur ses quatre pattes :cat2:

**Comment by linogaliana** [comment]
In GitLab by @RLesur on Jun 19, 2020, 15:44

Je n'ai pas pris le temps d'y réfléchir plus que ça, mais si je devais le tenter, je ferais un git hook dans un répertoire custom comme décrit [ici](https://stackoverflow.com/a/427269) (sauf le symlink) et je mettrais la commande `git config` décrite [ici](https://stackoverflow.com/a/37861972) dans le `.Rprofile`

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Jun 19, 2020, 15:47

Utiliser le `.Rprofile` est l'intuition que j'avais ; c'est pas la priorité mais ça peut être utile à long terme

**Comment by oliviermeslin** [comment]
@linogaliana : peut-on fermer cette _issue_? Il me semble que le problème est réglé en pratique par le fait que les mainteneurs veillent à n'avoir que des `.png`. Qu'en penses-tu?

**Comment by oliviermeslin** [comment]
J'avais fermé par erreur
