### ISSUE TITLE
renv sous AUS

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#76]
In GitLab by @linogaliana on Jul 2, 2020, 08:22

Après discussion avec Aurélien, j'ai l'impression que renv sera disponible sous AUS (à confirmer). Ce serait bien d'ajouter quelque chose là-dessus dans la partie AUS:

* comment utiliser un environnement
* comment modifier un environnement (pas sûr que ce sera possible en revanche pour un utilisateur n'ayant pas de droits d'écriture sur *Communs*)

J'ouvre cette *issue* pour garder ce point en tête

**Comment by linogaliana** [comment]
@oliviermeslin cette *issue* ne me semble plus d'actualité sous cette forme là puisque renv ne fonctionne pas sous aus. On ferme ?

La question de renv pourra être abordée dans la fiche de gestion des dépendances rédigée par @RLesur

**Comment by oliviermeslin** [comment]
Oui, bien sûr
