### ISSUE TITLE
Ordre des fiches

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#97]
In GitLab by @linogaliana on Nov 6, 2020, 08:51

On commence à avoir pas mal de fiches et converger, pour la partie Fiches Thématiques, vers une version complète pour la V0. 

Il faut commencer à réfléchir sur la question de l'ordre des fiches. @oliviermeslin a, je n'en doute pas, déjà réfléchi à la question. Tu as un comparatif des différentes possibilités à disposition ? :smiling_imp:

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Nov 13, 2020, 16:22

Merci @linogaliana. J'ai effectivement commencé à réfléchir au sujet. Il y a un ordre qui me semble logique, et qui préside déjà partiellement à l'organisation de cette partie: 

- 1/ récupérer des données (importation SAS, tableurs, fichiers plats); 
- 2/ manipulation de données (fiches `tidyverse` et `data.table`, joindre des tables, utiliser un SGBD, données textuelles, données spatiales, analyse de données);
- 3/ produire des _outputs_ (fiches `ggplot2` et `R Markdown`, partie cartographie).

Toutefois, cet ordre n'est pas pleinement satisfaisant, car il oublie plusieurs fiches de méthode qui me paraissent très importantes pour faire un bon usage de `R`:

- choisir son _workflow_ (`tidyverse` ou `data.table`, voire `spark`);
- choisir ses _packages_;
- gérer la mémoire avec `R`.

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Nov 14, 2020, 08:03

je trouve l'ordre proposé par @oliviermeslin pertinent (on importe, on traite, on génère des *outputs*).
Les fiches restantes relèvent d'un niveau plus avancé, et devraient, selon moi, être regroupées dans une dernière partie (pour aller plus loin, ou autre)

**Comment by oliviermeslin** [comment]
Je profite d'un instant de répit pour proposer une organisation d'ensemble de la documentation.

Il me semble préférable de structurer la documentation non pas en deux grandes parties, mais en 5-6 parties de taille raisonnable, chacune regroupant un nombre limités de fiches (3-4). Voici ce que je propose :

| __Partie__ 	| __Fiches__ 	|
|-	|-	|
| Utiliser `R` à l’Insee 	| Fiches AUSv3, SSPCloud, configurer Git, utiliser `Git` avec Rstudio, gérer les ressources 	|
| Être autonome avec `R` 	| Fiches installer des _packages_, choisir des _packages_, se documenter, gestion des dépendances 	|
| Importer des données 	| Fiches SAS, tableurs, fichiers plats, bases de données, API 	|
| Manipuler des données 	| Fiches `tidyverse`, `data.table`, joindre des données, données enquêtes, données textuelles, données spatiales 	|
| Produire des _outputs_ 	| Fiches graphiques, R Markdown, rapports paramétrés, cartographie 	|

**Comment by linogaliana** [comment]
Moi je mettrais plutôt la partie `Utiliser R à l’Insee` à la fin avec beaucoup de *cross-references* vers celles-ci dans l'ouvrage.

C'est une partie à laquelle on se réfère de temps en temps. La mettre au début est rebutant pour la personne découvrant l'ouvrage.

**Comment by oliviermeslin** [comment]
Ben c'est une bonne question. Deux contre-arguments:

- Il me paraissait logique de mettre cette partie en premier, car c'est chronologiquement la première question que se pose un agent: "Où est-ce que je vais dans l'ordinateur pour lancer RStudio"?
- Cette partie n'est pas si rebutante que ça, grâce à toutes les captures d'écran qu'elle contient 📸.

**Comment by oliviermeslin** [comment]
Sur ton deuxième point: mon premier jet de plan adoptait la même répartition que toi, mais je l'ai modifiée car, dans la mesure où `Git` est l'un des points les plus complexes et les plus effrayants de l'utilisation de `R`, il m'a semblé souhaitable que les deux fiches aillent ensemble (configurer + utiliser).

Attendons de voir ce que pensent les autres contributeurs.

**Comment by linogaliana** [comment]
D'ailleurs, je pense qu'un nom plus honnête pour la partie `Être autonome avec R`  serait `Mener un projet statistique avec R`. Cela rend cohérent l'intégration de la fiche `utiliser Git avec Rstudio` qui ne dépend pas d'un contexte Insee

**Comment by linogaliana** [comment]
> Sur ton deuxième point: mon premier jet de plan adoptait la même répartition que toi, mais je l'ai modifiée car, dans la mesure où Git est l'un des points les plus complexes et les plus effrayants de l'utilisation de R, il m'a semblé souhaitable que les deux fiches aillent ensemble (configurer + utiliser).

La fiche d'utilisation de `Git` est une fiche qui sert d'aide mémoire à consulter régulièrement. La mettre dans une partie où on a des fiches qui ne sont consultées que rarement, quand on désire configurer quelque chose, c'est rater la cible. Pour lier à la fiche configuration, les références croisées sont un outil plus efficace

**Comment by oliviermeslin** [comment]
Voici une nouvelle version du plan



| __Partie__ 	| __Fiches__ 	|
|-	|-	|
| Utiliser `R` à l’Insee 	| Fiches __AUSv3__, __SSPCloud__, __configurer Git__, gérer les ressources 	|
| Mener un projet statistique avec `R` 	| Fiches __utiliser les projets `RStudio`__, utiliser `Git` avec Rstudio, installer des _packages_, choisir des _packages_, __gérer les dépendances__, __se documenter__, personnaliser la configuration de `R` 	|
| Importer des données 	| Fiches SAS, tableurs, fichiers plats, bases de données, __API__ 	|
| Manipuler des données 	| Fiches `tidyverse`, `data.table`, joindre des données, données enquêtes, données textuelles, données spatiales 	|
| Produire des _outputs_ 	| Fiches graphiques, R Markdown, __rapports paramétrés__, __cartographie__ 	|

**Comment by sylvainDaubree** [comment]
de mon côté la proposition me va, j'ai juste une réserve sur commencer par *utiliser `R` à l'Insee* : il me semble que la doc est à destination SSP, pas que Insee même si c'est bien sûr notre public privilégiée, j'aurais du coup mis plutôt ça à la fin, presque en annexe. Autre option : avoir une version Insee et une version non Insee, avec une partie "détachable" ? 

Qu'y a t'il dans "gérer les ressources" ? je n'ai pas trouvé la fiche dans la doc.

**Comment by py-b** [comment]
@sylvainDaubree : je pense que c'est cette fiche : https://www.book.utilitr.org/superviser-ressources.html

**Comment by py-b** [comment]
Les contenus et titres des parties me vont bien. Je pense que l'ordre n'est pas si important que ça. Personne ne va lire le doccument dans l'ordre et d'une traite, les gens vont plutôt piocher une fiche ça et là selon leurs besoins.
Par conséquent, il est crucial que la structure du document et les objectifs des différentes parties apparaissent tout de suite et de manière évidente aux yeux du lecteur.

**Comment by sylvainDaubree** [comment]
merci @py-b ! j'avais un doute sur le fait que la fiche soit rangée dans la bonne case, mais du coup ça me va bien. 

 Je suis d'accord que le document n'est pas fait pour être lu d'une traite, mais par contre, je pense que les gens qui vont tomber dessus, au format papier ou numérique, vont quand même commencer par le sommaire. Et je me dis que si la première partie sur laquelle ils tombent c'est "comment ça marche à l'Insee", ça peut refroidir un peu. Bon depuis que je suis en SSM, j'ai peut-être développé une hypersensibilité à la question, donc je dramatise sans doute un brin :).

**Comment by linogaliana** [comment]
Je suis 💯 % d'accord avec @sylvainDaubree!

**Comment by oliviermeslin** [comment]
@sylvainDaubree : je suis d'accord avec toi, le public d'`utilitR` est beaucoup plus large que l'Insee. De mon point de vue, notre public est tous les utilisateurs francophones de `R`. Ceci dit, notre coeur de cible sont les agents de l'Insee _dans un premier temps_, car notre premier objectif est de faciliter la transition _de l'Insee_ vers `R`. C'est pour cela que la première partie est ciblées sur l'Insee, mais nous n'excluons aucunement les SSM. Par ailleurs, les éléments spécifiques à l'environnement de travail à l'Insee ne concerne qu'une petite minorité de fiches (plutôt au début de la doc).

Ceci dit, tu as raison de mentionner les besoins spécifiques des SSM. Mon opinion est la suivante:

- maintenir deux versions de la même documentation dans le même dépôt est un enfer informatique.
- dans la mesure où la plupart des contributeurs sont en poste à l'Insee, ce n'est pas à nous de documenter l'environnement de travail des SSM.
- la meilleure solution me paraît être que les SSM se fassent leur propre version d'`utilitR`, par exemple en forkant le dépôt et en modifiant les parties spécifiques à leur environnement de travail. Ce n'est pas un si gros travail que ça, et seuls les SSM qui ont vraiment l'usage de `R` le feront.

**Comment by py-b** [comment]
On peut aussi réfléchir en terme du nombre de consultations d'un utilisateur d'une fiche donnée. Je dirais qu'un utilisateur consultera plus fréquemment les fiches sur les import / manipulations de donnée / graphiques..., tandis que les fiches de config ne seront probablement consultées qu'une fois ou deux.
Si cette hypothèse se tient, les fiches les plus utilisées seraient à mettre au début.

**Comment by oliviermeslin** [comment]
Ah oui, ça peut être une bonne idée de mettre la partie _Utiliser `R` à l'Insee_ à la fin. Qu'en pense @linogaliana et @RLesur ?

@sylvainDaubree : en fait, quasiment tous les éléments spécifiques à l'Insee sont dans cette partie. Les SSM ont simplement besoin de la réécrire pour l'adapter à leur environnement de travail.

**Comment by sylvainDaubree** [comment]
@oliviermeslin oups je n'ai sans doute pas été clair, mon idée n'était pas de documenter l'environnement de travail des SSM, mais simplement de rendre facile le fait d'avoir une version imprimable de la doc sans la partie Insee (non pas en virant les petits bouts Insee qui sont, et c'est très bien, un peu partout, mais en ne mettant juste pas la première partie (qui pourrait à mon avis être plutôt la dernière)). Cela peut effectivement se faire avec un fork, d'autant que je suis d'accord avec toi qu'avoir un dépôt monolithique qui plaise à tout le monde risque de se retrouver en gros truc pénible à maintenir.

**Comment by oliviermeslin** [comment]
@sylvainDaubree : OK, donc en mettant la partie Insee à la fin, on obtient quelque chose d'assez générique. Et générer deux pdf différents, avec ou sans cette partie, n'est pas tellement difficile.

**Comment by oliviermeslin** [comment]
Voici une version mise à jour du plan. Le fait que "Utiliser `R` à l’Insee" soit en premier n'a aucune importance (on pourra déplacer cette partie).

| __Partie__ 	| __Fiches__ 	|
|-	|-	|
| Utiliser `R` à l’Insee 	| Fiches __AUSv3__, __SSPCloud__, configurer Git, gérer les ressources, personnaliser la configuration de `R` 	|
| Mener un projet statistique avec `R` 	| Fiches __utiliser les projets `RStudio`__, utiliser `Git` avec Rstudio, installer des _packages_, choisir des _packages_, __gérer les dépendances__, demander de l'aide, se documenter	|
| Importer des données 	| Fiches SAS, tableurs, fichiers plats, bases de données, __API__ 	|
| Manipuler des données 	| Fiches `tidyverse`, `data.table`, joindre des données, données enquêtes, données textuelles, données spatiales 	|
| Produire des _outputs_ 	| Fiches graphiques, R Markdown, __rapports paramétrés__, __cartographie__ 	|

**Comment by mathiasandre** [comment]
Suite à mes commentaires dans le salon voilà une proposition de plan de la doc :

**Comment by mathiasandre** [comment]
Suite à mes commentaires dans le salon tchap sur la place de GIT, voilà une proposition de plan à partir de la dernière proposition d'@oliviermeslin : 
- déplacement "demander aide" et "se documenter" dans utiliser R à l'Insee
- suppression de ce qui concerne GIT : il suffit de le mentionner dans la fiche projet ("il est recommandé d'utiliser la gestion de version avec GIT et Rstudio et donner des liens de doc). 

```
| __Partie__ 	| __Fiches__ 	|
|-	|-	|
| Utiliser `R` à l’Insee 	| Fiches __AUSv3__, __SSPCloud__, gérer les ressources, personnaliser la configuration de `R`, __demander de l'aide__, __se documenter__	|
| Mener un projet statistique avec `R` 	| Fiches __utiliser les projets `RStudio`__, installer des _packages_, choisir des _packages_, __gérer les dépendances__,  	|
| Importer des données 	| Fiches SAS, tableurs, fichiers plats, bases de données, __API__ 	|
| Manipuler des données 	| Fiches `tidyverse`, `data.table`, joindre des données, données enquêtes, données textuelles, données spatiales 	|
| Produire des _outputs_ 	| Fiches graphiques, R Markdown, __rapports paramétrés__, __cartographie__ 	|

**Comment by oliviermeslin** [comment]
Il me semble que l'ordre des fiches a été stabilisé, et puis j'ai envie de fermer une _issue_.
