### ISSUE TITLE
[R markdown] une section sur les rapports paramétrés ?

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/utilitR#99]
In GitLab by @gillesfidani on Nov 9, 2020, 07:18

tout est dans le titre

https://bookdown.org/yihui/rmarkdown/parameterized-reports.html

**Comment by linogaliana** [comment]
In GitLab by @linogaliana on Nov 9, 2020, 09:17

Merci @gillesfidani . En fait j'avais songé à mettre quelque chose dessus mais j'ai finalement retiré (bec738c7fdfb59241b1961d160e9f2cac24a3204).

Je pense que c'est intéressant à mentionner, je suis d'accord. J'attends de voir s'il y a des avis contradictoires. S'il n'y en a pas, j'ajouterai une section sur le sujet

**Comment by linogaliana** [comment]
In GitLab by @oliviermeslin on Nov 9, 2020, 10:23

C'est une bonne idée d'avoir quelque chose sur les rapports paramétrés. Ceci dit, je me dis trois choses:

- il y a un risque que la fiche `R Markdown` devienne très longue.
- il me semble qu'il y a deux besoins différents: rédiger des documents avec `R Markdown`, et préparer des rapports automatisés. Par exemple, un contributeurs d'`utilitR` a le premier besoin, mais pas forcément le second.
- Faire un rapport automatisé est une tâche précise qui peut faire gagner beaucoup de temps aux agents, ça vaut vraiment le coup qu'on fasse quelque chose de bien détaillé sur ce sujet.

Je propose donc qu'on fasse deux fiches séparées:

- une intro générale à `R Markdown` (en gros la fiche actuelle); 
- une fiche spécifiquement sur les rapports automatisés. Cette fiche pourrait prendre la forme d'un tutoriel bien détaillé, éventuellement avec un template associé.

Qu'en pensez-vous?

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Nov 9, 2020, 10:37

je ne suis pas fan de démultiplier les fiches, mais là, ça me semble judicieux. Il faudrait bien sûr rattacher les 2 au travers de liens (PESP ou autre)

Concernant le template, je trouve que c'est une excellente idée. C'est une aide précieuse pour quelqu'un qui souhaite avoir un aperçu d'une fonctionnalité. Si besoin, je peux mettre à dispo celui que je viens de créer pour générer des graphiques des indicateurs clés d'insee.fr (à partir de la BDM).

**Comment by linogaliana** [comment]
In GitLab by @py_b on Nov 9, 2020, 10:48

PESP ?

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Nov 9, 2020, 10:50

PESP : pour en savoir plus

désolé

**Comment by linogaliana** [comment]
In GitLab by @py_b on Nov 9, 2020, 11:12

Pas de souci, mon dictionnaire des sigles s'est enrichi.

**Comment by linogaliana** [comment]
In GitLab by @acazaubiel on Nov 10, 2020, 12:56

Est-ce vraiment *si* conséquent ? Une fiche juste pour ça, ça me semble un peu de l'overkill, non ?

**Comment by linogaliana** [comment]
In GitLab by @gillesfidani on Nov 14, 2020, 08:16

d'accord sur le fond avec @acazaubiel , c'est très (trop) généreux de consacrer une fiche entière pour un sujet aussi limité.

Mais les "consignes" de départ étaient de réaliser des fiches de type *cookbook* synthétiques, de 2/3 pages max. Au dela, leur lecture devient plus difficile, moins digeste.

2 solutions :

1. réduire ce sujet pour l'intégrer à la fiche mère `rmarkdown`
2. développer cette fiche pour la rendre pleinement "autonome".

**Comment by gilles13** [comment]
> 
> 
> In GitLab by @gillesfidani on Nov 14, 2020, 08:16
> 
> d'accord sur le fond avec @acazaubiel , c'est très (trop) généreux de consacrer une fiche entière pour un sujet aussi limité.
> 
> Mais les "consignes" de départ étaient de réaliser des fiches de type _cookbook_ synthétiques, de 2/3 pages max. Au dela, leur lecture devient plus difficile, moins digeste.
> 
> 2 solutions :
> 
>     1. réduire ce sujet pour l'intégrer à la fiche mère `rmarkdown`
> 
>     2. développer cette fiche pour la rendre pleinement "autonome".

la question se pose encore suite aux échange dans la PR :

https://github.com/InseeFrLab/utilitR/pull/178#issuecomment-740894945

pour ma part, rappeler le principe des rapports automatisés dans la fiche rapports paramétré me semble redondant.

**Comment by oliviermeslin** [comment]
Je n'ai pas l'impression que ce soit redondant sous les conditions suivantes: 

- la fiche prend la forme d'un tutoriel sur "Comment faire un rapport paramétré";
- la fiche renvoie systématiquement à la fiche `Rmd` sur le fonctionnement de Rmd;
- la fiche contient essentiellement des conseils sur comment structurer le rapport, et des exemples reproductibles.

Comme points importants, je vois notamment:
- comment bien structurer le yaml du début;
- comment organiser l'appel aux données;
- quelques conseils sur le _chunk_ de _setup_;
- comment bien structurer la définition des paramètres s'il en a.

**Comment by linogaliana** [comment]
Je suis d'accord avec @oliviermeslin . La fiche R Markdown est déjà bien fournie, mais elle présente le principe général de R Markdown. L'approche cas d'usages, comme un rapport automatisé, mérite une fiche propre, se concentrant sur les conseils complémentaires à ceux de la fiche Rmd. 

Donc, comme Olivier, je suis d'avis de faire une fiche spécifique.

**Comment by py-b** [comment]
Je colle ici mes réponses dans tchap en novembre (pas fondamentalement changé d'avis depuis) :

- _"ou bien mentionner l'existence et le principe, puis renvoyer vers une doc bien faite (comment ça, partisan du moindre effort ?)_" (9 novembre 2021 11:26)
- _"honnêtement la meilleure explication en français serait une traduction du chapitre du livre de Yihui Xie"_ (9 novembre 2021 12:30)

**Comment by oliviermeslin** [comment]
@py-b : tu aurais le lien du chapitre du libre de Yihui Xie?

**Comment by py-b** [comment]
@oliviermeslin : il est dans le premier message de l'issue.

**Comment by pierre-lamarche** [comment]
Pour ma part je suis d'accord avec @oliviermeslin et @linogaliana sur la pertinence d'une fiche à part ; il me semble qu'une rédaction un peu didactique façon tutoriel serait extrêmement utile, tout en laissant les références en fin de fiche pour les utilisateurs qui voudraient approfondir - y compris la référence anglophone de @py-b .

**Comment by RLesur** [comment]
En ce qui me concerne, je proposerais volontiers de reprendre l'angle "besoins/tâches à accomplir". Prendre les choses sous l'angle "rapports paramétrés" me semble trop technique. De mon point de vue, les tâches couvertes sont : 

- la production de rapports en masse (sur des zones géographiques différentes, par exemple)
- la production régulière/l'actualisation d'un rapport

Pour R Markdown, il me semble que la tâche correspondante est plutôt celle de réaliser une étude reproductible.

**Comment by py-b** [comment]
Réglé par #278 ?

**Comment by linogaliana** [comment]
oui, je ferme
